# Resampling of Flair

In [1]:
import os
import numpy as np
import pandas as pd
from datetime import datetime

### Read Existing Tables

In [2]:
file_path = "../../data/out/FLAIRPublicDataSet/"
file_map = {
    'cgm': 'Flair_cgm_history.csv.gz',
    'bolus': 'Flair_bolus_event_history.csv.gz',
    'basal': 'Flair_basal_event_history.csv.gz',
}

In [3]:
def get_df_from_file(file_path, file_name, parse_datetime=True, sep=','):
    df = pd.read_csv(file_path + file_name, sep=sep)
    if parse_datetime:
        df['date'] = pd.to_datetime(df['datetime'], unit='s')
    return df

In [4]:
def get_extended_df(original_df, value_column):
    """
    Get a df where quantities are distributed throughout 5-minute intervals instead of having start- and end dates.
    """
    new_rows = []
    for _, row in original_df.iterrows():
        new_rows.extend(split_duration(row, value_column))
    extended_df = pd.DataFrame(new_rows)
    extended_df.set_index('date', inplace=True)
    return extended_df

def split_duration(row, value_column):
    """
    For features with a duration, we split the values across 5-minute intervals by adding
    new rows for every 5-minute window in duration, and equally split the original quantity across those rows.
    """
    duration = row['end_date'] - row['date']
    rounded_duration = round(duration / pd.Timedelta(minutes=5)) * pd.Timedelta(minutes=5)
    num_intervals = rounded_duration // pd.Timedelta(minutes=5)
    if num_intervals < 1:
        num_intervals = 1
    value_per_interval = row[value_column] / num_intervals
    new_rows = []
    for i in range(int(num_intervals)):
        new_row = {
            'date': row['date'] + pd.Timedelta(minutes=5 * i),
            value_column: value_per_interval,
            'patient_id': row['patient_id'],
        }
        new_rows.append(new_row)
    return new_rows

In [5]:
def parse_flair_dates(dates, format_date = '%m/%d/%Y', format_time = '%I:%M:%S %p'):
    """Parse date strings separately for those with/without time component, interpret those without as midnight (00AM)
    Args:
        dates (pd.DataFrame): datetimes (string) either in in the %m/%d/%Y or %m/%d/%Y %I:%M:%S %p format
    Returns:
        pandas series: with parsed dates
    """
    #make sure to only parse dates if the value is not null
    dates = dates.astype(str)
    only_date = dates.apply(len) <=10
    dates_copy = dates.copy()
    dates_copy.loc[only_date] = pd.to_datetime(dates.loc[only_date], format=format_date)
    dates_copy.loc[~only_date] = pd.to_datetime(dates.loc[~only_date], format=f'{format_date} {format_time}')
    return dates_copy.astype('datetime64[ns]')

In [6]:
df_glucose = get_df_from_file(file_path, file_map['cgm'])
df_bolus = get_df_from_file(file_path, file_map['bolus'])
df_basal = get_df_from_file(file_path, file_map['basal'])

### Resample Existing Tables

In [7]:
df_glucose.set_index('date', inplace=True)
df_glucose.head()

                     patient_id    datetime  cgm
date
2019-05-15 21:18:15          26  1557955095  136
2019-05-15 21:13:15          26  1557954795  146
2019-05-15 21:08:15          26  1557954495  157
2019-05-15 21:03:15          26  1557954195  166
2019-05-15 20:58:15          26  1557953895  174

In [8]:
df_bolus_orig = df_bolus.copy()
df_bolus['end_date'] = df_bolus['date'] + pd.to_timedelta(df_bolus['delivery_duration'], unit='s')
df_bolus = get_extended_df(df_bolus, 'bolus')
df_bolus

                     bolus  patient_id
date
2018-06-04 13:33:20    7.7          88
2018-06-04 14:03:02    2.2          88
2018-06-04 19:08:38    6.6          88
2018-06-04 20:42:51    0.3          88
2018-06-04 23:01:28    5.1          88
...                    ...         ...
2020-03-29 14:12:48    5.3           4
2020-03-29 18:37:00   10.4           4
2020-03-30 15:20:20    4.6           4
2020-03-30 19:46:16    8.6           4
2020-03-31 09:42:28    6.8           4

[3393277 rows x 2 columns]

In [9]:
print(f'New sum after distribution of extended boluses: {df_bolus["bolus"].sum():.2f}, should be: {df_bolus_orig["bolus"].sum():.2f}')

New sum after distribution of extended boluses: 1235667.82, should be: 1235667.82

In [10]:
df_basal_orig = df_basal.copy()
df_basal.sort_values(by=['patient_id', 'date'], inplace=True)
df_basal.set_index('date', inplace=True)
df_basal

                     patient_id    datetime  basal_rate
date
2018-08-08 14:10:00           1  1533737400        0.00
2018-08-08 15:11:00           1  1533741060        1.30
2018-08-08 15:18:10           1  1533741490        0.00
2018-08-08 15:22:22           1  1533741742        1.30
2018-08-08 16:08:38           1  1533744518        0.00
...                         ...         ...         ...
2019-05-27 18:57:31         126  1558983451        0.00
2019-05-27 19:23:26         126  1558985006        1.05
2019-05-27 22:00:00         126  1558994400        1.25
2019-05-27 23:07:14         126  1558998434        0.00
2019-05-28 08:53:00         126  1559033580        1.30

[142653 rows x 3 columns]

In [11]:
processed_dfs = []
subject_ids = df_glucose['patient_id'].unique()
print("Subjects:", len(subject_ids))
for subject_id in subject_ids:
    df_subject = df_glucose[df_glucose['patient_id'] == subject_id].copy()
    df_subject = df_subject[['cgm']].resample('5min', label='right').mean()
    df_subject['patient_id'] = subject_id
    df_subject.sort_index(inplace=True)

    def merge_data(df_col, df_subject, col_names, subject_id, agg_type='sum'):
        """ agg_type is data aggregation type. """
        df_subset = df_col[df_col['patient_id'] == subject_id].copy()
        if not df_subset.empty:
            if agg_type == 'mean':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').mean()
            elif agg_type == 'sum':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').sum()
            elif agg_type == 'first':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').first()
            elif agg_type == 'last':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').last()
            else:
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').sum()
            df_subject = pd.merge(df_subject, df_subset, on="date", how='outer')
        else:
            df_subject[col_names] = np.nan
        return df_subject

    # Add insulin and insulin type
    df_subject = merge_data(df_bolus, df_subject, ['bolus'], subject_id, agg_type='sum')
    df_subject = merge_data(df_basal, df_subject, ['basal_rate'], subject_id, agg_type='last')
    df_subject['basal_rate'] = df_subject['basal_rate'].ffill()
    
    df_subject['patient_id'] = subject_id
    df_subject = df_subject.rename(columns={'patient_id': 'id', 'basal_rate': 'basal', 'cgm': 'CGM'})
    processed_dfs.append(df_subject)
    print(f"{subject_id} is finished processing")

df_final = pd.concat(processed_dfs)

Subjects: 113
26 is finished processing
40 is finished processing
78 is finished processing
46 is finished processing
15 is finished processing
33 is finished processing
37 is finished processing
85 is finished processing
36 is finished processing
20 is finished processing
126 is finished processing
11 is finished processing
97 is finished processing
73 is finished processing
120 is finished processing
79 is finished processing
16 is finished processing
14 is finished processing
81 is finished processing
88 is finished processing
105 is finished processing
13 is finished processing
95 is finished processing
99 is finished processing
48 is finished processing
18 is finished processing
56 is finished processing
90 is finished processing
93 is finished processing
9 is finished processing
72 is finished processing
102 is finished processing
115 is finished processing
69 is finished processing
23 is finished processing
86 is finished processing
84 is finished processing
38 is finished processing
30 is finished processing
106 is finished processing
82 is finished processing
31 is finished processing
83 is finished processing
54 is finished processing
55 is finished processing
116 is finished processing
4 is finished processing
123 is finished processing
6 is finished processing
112 is finished processing
121 is finished processing
66 is finished processing
101 is finished processing
114 is finished processing
111 is finished processing
21 is finished processing
50 is finished processing
22 is finished processing
62 is finished processing
103 is finished processing
19 is finished processing
35 is finished processing
100 is finished processing
10 is finished processing
60 is finished processing
109 is finished processing
45 is finished processing
5 is finished processing
98 is finished processing
29 is finished processing
119 is finished processing
94 is finished processing
92 is finished processing
12 is finished processing
51 is finished processing
58 is finished processing
52 is finished processing
44 is finished processing
71 is finished processing
107 is finished processing
17 is finished processing
3 is finished processing
27 is finished processing
108 is finished processing
47 is finished processing
96 is finished processing
57 is finished processing
65 is finished processing
74 is finished processing
75 is finished processing
1 is finished processing
125 is finished processing
91 is finished processing
25 is finished processing
124 is finished processing
28 is finished processing
77 is finished processing
2 is finished processing
63 is finished processing
61 is finished processing
117 is finished processing
49 is finished processing
87 is finished processing
104 is finished processing
67 is finished processing
43 is finished processing
68 is finished processing
64 is finished processing
7 is finished processing
122 is finished processing
39 is finished processing
59 is finished processing
113 is finished processing

In [12]:
df_final

                       CGM   id  bolus  basal
date
2019-02-08 14:05:00    NaN   26    NaN   1.15
2019-02-08 14:10:00    NaN   26    NaN   1.15
2019-02-08 14:15:00    NaN   26    NaN   1.15
2019-02-08 14:20:00    NaN   26    NaN   1.15
2019-02-08 14:25:00    NaN   26    NaN   1.15
...                    ...  ...    ...    ...
2019-07-26 08:00:00  171.0  113   0.15   0.00
2019-07-26 08:05:00  180.0  113   0.45   0.00
2019-07-26 08:10:00  185.0  113   0.13   0.00
2019-07-26 08:15:00  187.0  113   0.15   0.00
2019-07-26 08:20:00  182.0  113   0.15   0.00

[7000967 rows x 4 columns]

### Add Additional Tables

We found:
- Insulin type
- Age
- Weight
- Height
- Gender

In [13]:
raw_data_file_path = "../../data/raw/FLAIRPublicDataSet/Data Tables/"

In [14]:
df_insulin_type = get_df_from_file(raw_data_file_path, 'FLAIRInsulin.txt', parse_datetime=False, sep='|')
df_insulin_type = df_insulin_type[['PtID', 'InsulinName']]
df_insulin_type = df_insulin_type.rename(columns={'PtID': 'id', 'InsulinName': 'insulin_type'})
df_insulin_type

      id      insulin_type
0    103  Humalog (Lispro)
1     88  Novolog (Aspart)
2    105  Novolog (Aspart)
3     13  Novolog (Aspart)
4     31  Novolog (Aspart)
..   ...               ...
191   14  Humalog (Lispro)
192   48  Humalog (Lispro)
193   86  Novolog (Aspart)
194   30  Novolog (Aspart)
195    7  Novolog (Aspart)

[196 rows x 2 columns]

In [15]:
def add_single_value_to_subjects(df, df_new_val, col_name):
    # TODO: this function is very inefficient... add value directly to located rows instead
    processed_dfs = []
    subject_ids = df['id'].unique()
    for subject_id in subject_ids:
        df_subject = df[df['id'] == subject_id].copy()
        df_subject.sort_index(inplace=True)
    
        user_data = df_new_val[df_new_val['id'] == subject_id].copy()
        if not user_data.empty:
            if pd.api.types.is_numeric_dtype(user_data[col_name]):
                print(f"Mean val from {len(user_data[col_name])} values: ", user_data[col_name].mean(skipna=True))
                df_subject[col_name] = user_data[col_name].mean(skipna=True)
            else:
                print(f"String val with {len(user_data[col_name])}: ", ", ".join(user_data[col_name].dropna().astype(str)))
                df_subject[col_name] = ", ".join(user_data[col_name].dropna().astype(str))  # Take the first value for non-numeric data
        else:
            df_subject[col_name] = np.nan        
        processed_dfs.append(df_subject)
        
    df = pd.concat(processed_dfs)
    return df

In [16]:
# TODO in future work: should we handle MDI? How? 
# TODO: When subjects change insulin we should also handle that! 
# TODO: I think that insulin type should be a part of the bolus / basal tables, so that we can specify at that point

In [17]:
# Add insulin type
df_final = add_single_value_to_subjects(df_final, df_insulin_type, 'insulin_type')
df_final

String val with 1:  Novolog (Aspart)
String val with 2:  Novolog Fiasp, Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 3:  Humalog (Lispro), Humalog (Lispro), Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 2:  Humalog (Lispro), Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 3:  Novolog (Aspart), Humalog (Lispro), Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 2:  Novolog (Aspart), Humalog (Lispro)
String val with 3:  Degludec (Tresiba), Humalog (Lispro), Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 6:  Humalog (Lispro), Degludec (Tresiba), Humalog (Lispro), Humalog (Lispro), Degludec (Tresiba), Humalog (Lispro)
String val with 4:  Humalog (Lispro), Lantus (Glargine) 1 time per day, Humalog (Lispro), Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 3:  Humalog (Lispro), Basaglar (Glargine, U100), Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 5:  Novolog Fiasp, Toujeo (Glargine, U300), Humalog (Lispro), Novolog (Aspart), Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 5:  Lantus (Glargine) 1 time per day, Humalog (Lispro), Novolog (Aspart), Lantus (Glargine) 1 time per day, Humalog (Lispro)
String val with 3:  Novolog (Aspart), Basaglar (Glargine, U100), Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 3:  Novolog (Aspart), Degludec (Tresiba), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 3:  Humalog (Lispro), Degludec (Tresiba), Humalog (Lispro)
String val with 3:  Degludec (Tresiba), Humalog (Lispro), Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 3:  Humalog (Lispro), Lantus (Glargine) 2 times per day, Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 2:  Admelog, Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 3:  Levemir (Detemir) 2 times per day, Humalog (Lispro), Humalog (Lispro)
String val with 3:  Novolog (Aspart), Degludec (Tresiba), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 3:  Novolog (Aspart), Lantus (Glargine) 1 time per day, Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 2:  Degludec (Tresiba), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 2:  Novolog (Aspart), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 1:  Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)
String val with 3:  Degludec (Tresiba), Humulin N (NPH), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 3:  Degludec (Tresiba), Novolog (Aspart), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 3:  Apidra (Glulisine), Novolog (Aspart), Apidra (Glulisine)
String val with 1:  Novolog (Aspart)
String val with 5:  Lantus (Glargine) 1 time per day, Regular (R) (Humulin R or Novolin R), Novolog (Aspart), Regular (R) (Humulin R or Novolin R), Lantus (Glargine) 1 time per day
String val with 1:  Humalog (Lispro)
String val with 5:  Regular (R) (Humulin R or Novolin R), Lantus (Glargine) 1 time per day, Novolog (Aspart), Regular (R) (Humulin R or Novolin R), Lantus (Glargine) 1 time per day
String val with 1:  Novolog (Aspart)
String val with 3:  Regular (R) (Humulin R or Novolin R), Levemir (Detemir) 1 time per day, Novolog (Aspart)
String val with 5:  Regular (R) (Humulin R or Novolin R), Lantus (Glargine) 1 time per day, Lantus (Glargine) 1 time per day, Regular (R) (Humulin R or Novolin R), Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 3:  Basaglar (Glargine, U100), Novolog (Aspart), Novolog (Aspart)
String val with 1:  Novolog (Aspart)
String val with 2:  Admelog, Humalog (Lispro)
String val with 1:  Novolog (Aspart)
String val with 1:  Humalog (Lispro)

                       CGM   id  bolus  basal      insulin_type
date
2019-02-08 14:05:00    NaN   26    NaN   1.15  Novolog (Aspart)
2019-02-08 14:10:00    NaN   26    NaN   1.15  Novolog (Aspart)
2019-02-08 14:15:00    NaN   26    NaN   1.15  Novolog (Aspart)
2019-02-08 14:20:00    NaN   26    NaN   1.15  Novolog (Aspart)
2019-02-08 14:25:00    NaN   26    NaN   1.15  Novolog (Aspart)
...                    ...  ...    ...    ...               ...
2019-07-26 08:00:00  171.0  113   0.15   0.00  Humalog (Lispro)
2019-07-26 08:05:00  180.0  113   0.45   0.00  Humalog (Lispro)
2019-07-26 08:10:00  185.0  113   0.13   0.00  Humalog (Lispro)
2019-07-26 08:15:00  187.0  113   0.15   0.00  Humalog (Lispro)
2019-07-26 08:20:00  182.0  113   0.15   0.00  Humalog (Lispro)

[7000967 rows x 5 columns]

In [18]:
# Add age
df_age = get_df_from_file(raw_data_file_path, 'PtRoster.txt', parse_datetime=False, sep='|')
df_age = df_age[['PtID', 'AgeAsofEnrollDt']]
df_age = df_age.rename(columns={'PtID': 'id', 'AgeAsofEnrollDt': 'age'})
df_age

      id  age
0     32   14
1     26   18
2     40   20
3     78   20
4     46   14
..   ...  ...
121  104   15
122   67   20
123   43   21
124   68   20
125   64   16

[126 rows x 2 columns]

In [19]:
# Add age
df_final = add_single_value_to_subjects(df_final, df_age, 'age')
df_final.head()

Mean val from 1 values:  18.0
Mean val from 1 values:  20.0
Mean val from 1 values:  20.0
Mean val from 1 values:  14.0
Mean val from 1 values:  15.0
Mean val from 1 values:  20.0
Mean val from 1 values:  16.0
Mean val from 1 values:  25.0
Mean val from 1 values:  16.0
Mean val from 1 values:  21.0
Mean val from 1 values:  14.0
Mean val from 1 values:  23.0
Mean val from 1 values:  20.0
Mean val from 1 values:  25.0
Mean val from 1 values:  26.0
Mean val from 1 values:  23.0
Mean val from 1 values:  24.0
Mean val from 1 values:  17.0
Mean val from 1 values:  14.0
Mean val from 1 values:  15.0
Mean val from 1 values:  23.0
Mean val from 1 values:  16.0
Mean val from 1 values:  14.0
Mean val from 1 values:  16.0
Mean val from 1 values:  29.0
Mean val from 1 values:  26.0
Mean val from 1 values:  16.0
Mean val from 1 values:  24.0
Mean val from 1 values:  27.0
Mean val from 1 values:  17.0
Mean val from 1 values:  15.0
Mean val from 1 values:  15.0
Mean val from 1 values:  26.0
Mean val from 1 values:  28.0
Mean val from 1 values:  25.0
Mean val from 1 values:  18.0
Mean val from 1 values:  19.0
Mean val from 1 values:  19.0
Mean val from 1 values:  19.0
Mean val from 1 values:  17.0
Mean val from 1 values:  15.0
Mean val from 1 values:  28.0
Mean val from 1 values:  21.0
Mean val from 1 values:  21.0
Mean val from 1 values:  16.0
Mean val from 1 values:  15.0
Mean val from 1 values:  27.0
Mean val from 1 values:  19.0
Mean val from 1 values:  22.0
Mean val from 1 values:  15.0
Mean val from 1 values:  18.0
Mean val from 1 values:  20.0
Mean val from 1 values:  15.0
Mean val from 1 values:  22.0
Mean val from 1 values:  21.0
Mean val from 1 values:  20.0
Mean val from 1 values:  16.0
Mean val from 1 values:  22.0
Mean val from 1 values:  15.0
Mean val from 1 values:  23.0
Mean val from 1 values:  29.0
Mean val from 1 values:  21.0
Mean val from 1 values:  19.0
Mean val from 1 values:  25.0
Mean val from 1 values:  23.0
Mean val from 1 values:  15.0
Mean val from 1 values:  24.0
Mean val from 1 values:  19.0
Mean val from 1 values:  26.0
Mean val from 1 values:  18.0
Mean val from 1 values:  18.0
Mean val from 1 values:  17.0
Mean val from 1 values:  18.0
Mean val from 1 values:  19.0
Mean val from 1 values:  15.0
Mean val from 1 values:  21.0
Mean val from 1 values:  21.0
Mean val from 1 values:  21.0
Mean val from 1 values:  17.0
Mean val from 1 values:  22.0
Mean val from 1 values:  15.0
Mean val from 1 values:  14.0
Mean val from 1 values:  14.0
Mean val from 1 values:  16.0
Mean val from 1 values:  16.0
Mean val from 1 values:  29.0
Mean val from 1 values:  15.0
Mean val from 1 values:  17.0
Mean val from 1 values:  15.0
Mean val from 1 values:  18.0
Mean val from 1 values:  19.0
Mean val from 1 values:  16.0
Mean val from 1 values:  23.0
Mean val from 1 values:  17.0
Mean val from 1 values:  15.0
Mean val from 1 values:  14.0
Mean val from 1 values:  16.0
Mean val from 1 values:  22.0
Mean val from 1 values:  28.0
Mean val from 1 values:  16.0
Mean val from 1 values:  16.0
Mean val from 1 values:  18.0
Mean val from 1 values:  14.0
Mean val from 1 values:  15.0
Mean val from 1 values:  20.0
Mean val from 1 values:  21.0
Mean val from 1 values:  20.0
Mean val from 1 values:  16.0
Mean val from 1 values:  23.0
Mean val from 1 values:  17.0
Mean val from 1 values:  14.0
Mean val from 1 values:  19.0
Mean val from 1 values:  17.0

                     CGM  id  bolus  basal      insulin_type   age
date
2019-02-08 14:05:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0
2019-02-08 14:10:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0
2019-02-08 14:15:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0
2019-02-08 14:20:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0
2019-02-08 14:25:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0

In [20]:
# Add gender
df_gender = get_df_from_file(raw_data_file_path, 'FLAIRDiabScreening.txt', parse_datetime=False, sep='|')
df_gender = df_gender[['PtID', 'Sex']]
df_gender = df_gender.rename(columns={'PtID': 'id', 'Sex': 'gender'})
df_gender

      id gender
0    103      F
1    105      F
2     88      M
3     31      F
4     83      F
..   ...    ...
114   62      M
115  113      F
116   59      F
117   22      M
118    4      M

[119 rows x 2 columns]

In [21]:
# Add weight, height, and gender
df_final = add_single_value_to_subjects(df_final, df_gender, 'gender')
df_final.head()

String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  M
String val with 1:  F
String val with 1:  F
String val with 1:  F
String val with 1:  F

                     CGM  id  bolus  basal      insulin_type   age gender
date
2019-02-08 14:05:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0      F
2019-02-08 14:10:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0      F
2019-02-08 14:15:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0      F
2019-02-08 14:20:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0      F
2019-02-08 14:25:00  NaN  26    NaN   1.15  Novolog (Aspart)  18.0      F

In [22]:
# Add weight and height
df_weight_height = get_df_from_file(raw_data_file_path, 'FLAIRDiabPhysExam.txt', parse_datetime=False, sep='|')

print(df_weight_height['HeightUnits'].unique())
print(df_weight_height['WeightUnits'].unique())

# If inches or lbs, --> cm and kg
df_weight_height['Height'] = df_weight_height.apply(
    lambda row: row['Height'] * 2.54 if row['HeightUnits'] != 'cm' else row['Height'],
    axis=1
)
df_weight_height['Weight'] = df_weight_height.apply(
    lambda row: row['Weight'] * 0.453592 if row['WeightUnits'] != 'kg' else row['Weight'],
    axis=1
)
df_weight_height[['Weight', 'Height']] = df_weight_height[['Weight', 'Height']].round(1)
df_weight_height = df_weight_height[['PtID', 'Weight', 'Height', 'Visit']]
df_weight_height = df_weight_height.rename(columns={'PtID': 'id', 'Weight': 'weight', 'Height': 'height'})
df_weight_height

['cm' 'in' nan]
['lbs' 'kg' nan]

      id  weight  height         Visit
0    103    82.1   167.0     Screening
1    105    75.3   163.1     Screening
2     88    57.6   170.0     Screening
3     31    82.1   159.0     Screening
4     83   120.4   182.5     Screening
..   ...     ...     ...           ...
450   38    61.4   164.0  End of Study
451    4    80.1   174.0  End of Study
452    7   112.2   181.1  End of Study
453   39    67.9   166.0  End of Study
454   59    76.0   166.8  End of Study

[455 rows x 4 columns]

In [23]:
df_weight_height[df_weight_height.duplicated('id', keep=False)].sort_values(by=['id', 'Visit'])

      id  weight  height                                       Visit
414    1    64.8   168.0                                End of Study
177    1    60.2   168.0  Period 1: Closed Loop Treatment Initiation
302    1    59.0   168.0  Period 2: Closed Loop Treatment Initiation
146    1    60.5   168.0                                   Screening
393    2    69.1   177.8                                End of Study
..   ...     ...     ...                                         ...
30   125    58.0   155.0                                   Screening
420  126    68.1   174.4                                End of Study
188  126    60.4   173.6  Period 1: Closed Loop Treatment Initiation
313  126    65.7   174.1  Period 2: Closed Loop Treatment Initiation
45   126    58.6   172.3                                   Screening

[449 rows x 4 columns]

In [24]:
# TODO in future work: For each subject, the weight and height and age should be given for the correct dates! and updated when measurements are updated!

In [25]:
# Add weight, height, and gender
df_final = add_single_value_to_subjects(df_final, df_weight_height, 'weight')
df_final = add_single_value_to_subjects(df_final, df_weight_height, 'height')
df_final[['weight', 'height']] = df_final[['weight', 'height']].round(1)
df_final.head()

Mean val from 4 values:  82.775
Mean val from 4 values:  76.80000000000001
Mean val from 4 values:  75.625
Mean val from 4 values:  75.275
Mean val from 4 values:  51.625
Mean val from 3 values:  99.8
Mean val from 4 values:  57.224999999999994
Mean val from 4 values:  67.55
Mean val from 4 values:  90.125
Mean val from 4 values:  76.825
Mean val from 4 values:  63.199999999999996
Mean val from 4 values:  85.975
Mean val from 4 values:  66.0
Mean val from 4 values:  83.7
Mean val from 4 values:  74.375
Mean val from 4 values:  82.225
Mean val from 4 values:  127.07500000000002
Mean val from 4 values:  92.575
Mean val from 4 values:  60.275000000000006
Mean val from 4 values:  59.65
Mean val from 4 values:  77.07499999999999
Mean val from 4 values:  81.675
Mean val from 4 values:  59.0
Mean val from 4 values:  85.30000000000001
Mean val from 4 values:  83.94999999999999
Mean val from 4 values:  60.825
Mean val from 4 values:  64.75
Mean val from 4 values:  72.65
Mean val from 4 values:  67.25
Mean val from 4 values:  75.925
Mean val from 4 values:  72.69999999999999
Mean val from 4 values:  54.8
Mean val from 4 values:  86.22500000000001
Mean val from 4 values:  73.25
Mean val from 4 values:  87.925
Mean val from 4 values:  69.4
Mean val from 4 values:  73.35000000000001
Mean val from 4 values:  61.5
Mean val from 4 values:  77.125
Mean val from 4 values:  93.15
Mean val from 4 values:  83.57499999999999
Mean val from 4 values:  85.4
Mean val from 4 values:  122.22500000000001
Mean val from 4 values:  80.32499999999999
Mean val from 4 values:  55.574999999999996
Mean val from 4 values:  67.125
Mean val from 4 values:  79.25
Mean val from 4 values:  75.925
Mean val from 4 values:  96.125
Mean val from 2 values:  60.25
Mean val from 4 values:  97.7
Mean val from 4 values:  68.925
Mean val from 4 values:  56.875
Mean val from 4 values:  60.35000000000001
Mean val from 4 values:  64.5
Mean val from 4 values:  84.975
Mean val from 4 values:  55.725
Mean val from 4 values:  78.1
Mean val from 4 values:  86.87500000000001
Mean val from 4 values:  80.3
Mean val from 4 values:  53.05
Mean val from 4 values:  68.025
Mean val from 4 values:  83.30000000000001
Mean val from 4 values:  74.4
Mean val from 4 values:  70.1
Mean val from 4 values:  68.95
Mean val from 4 values:  56.70000000000001
Mean val from 4 values:  69.275
Mean val from 4 values:  98.75
Mean val from 4 values:  75.4
Mean val from 4 values:  72.05
Mean val from 4 values:  60.099999999999994
Mean val from 4 values:  81.625
Mean val from 4 values:  93.325
Mean val from 4 values:  55.2
Mean val from 4 values:  62.15
Mean val from 4 values:  56.175
Mean val from 4 values:  80.9
Mean val from 4 values:  90.0
Mean val from 4 values:  71.30000000000001
Mean val from 4 values:  58.65
Mean val from 4 values:  55.075
Mean val from 4 values:  62.75
Mean val from 4 values:  89.075
Mean val from 4 values:  54.525
Mean val from 4 values:  95.225
Mean val from 4 values:  100.525
Mean val from 4 values:  71.4
Mean val from 4 values:  65.375
Mean val from 4 values:  59.475
Mean val from 4 values:  61.125
Mean val from 4 values:  60.525000000000006
Mean val from 4 values:  48.575
Mean val from 4 values:  73.925
Mean val from 4 values:  49.6
Mean val from 4 values:  53.325
Mean val from 4 values:  73.425
Mean val from 4 values:  68.4
Mean val from 4 values:  61.15
Mean val from 4 values:  81.25
Mean val from 4 values:  53.325
Mean val from 4 values:  81.975
Mean val from 4 values:  59.025
Mean val from 4 values:  68.475
Mean val from 4 values:  78.025
Mean val from 4 values:  55.925
Mean val from 4 values:  82.875
Mean val from 4 values:  77.75
Mean val from 4 values:  106.05
Mean val from 4 values:  59.625
Mean val from 4 values:  66.85
Mean val from 4 values:  73.05
Mean val from 4 values:  72.775
Mean val from 4 values:  163.8
Mean val from 4 values:  160.375
Mean val from 4 values:  179.025
Mean val from 4 values:  157.8
Mean val from 4 values:  158.45
Mean val from 3 values:  167.6
Mean val from 4 values:  155.675
Mean val from 4 values:  164.575
Mean val from 4 values:  179.7
Mean val from 4 values:  189.6
Mean val from 4 values:  173.6
Mean val from 4 values:  168.60000000000002
Mean val from 4 values:  169.275
Mean val from 4 values:  174.2
Mean val from 4 values:  172.9
Mean val from 4 values:  170.42499999999998
Mean val from 4 values:  182.60000000000002
Mean val from 4 values:  163.0
Mean val from 4 values:  164.2
Mean val from 4 values:  171.55
Mean val from 4 values:  164.275
Mean val from 4 values:  180.775
Mean val from 4 values:  162.825
Mean val from 4 values:  165.575
Mean val from 4 values:  166.22500000000002
Mean val from 4 values:  164.25
Mean val from 4 values:  166.95
Mean val from 4 values:  177.45
Mean val from 4 values:  163.225
Mean val from 4 values:  169.5
Mean val from 4 values:  185.67499999999998
Mean val from 4 values:  170.475
Mean val from 4 values:  181.1
Mean val from 4 values:  166.0
Mean val from 4 values:  164.97500000000002
Mean val from 4 values:  178.775
Mean val from 4 values:  171.975
Mean val from 4 values:  164.20000000000002
Mean val from 4 values:  158.775
Mean val from 4 values:  174.02499999999998
Mean val from 4 values:  183.1
Mean val from 4 values:  159.25
Mean val from 4 values:  181.975
Mean val from 4 values:  161.875
Mean val from 4 values:  162.275
Mean val from 4 values:  179.425
Mean val from 4 values:  174.275
Mean val from 4 values:  179.5
Mean val from 4 values:  165.45
Mean val from 2 values:  156.0
Mean val from 4 values:  158.925
Mean val from 4 values:  172.0
Mean val from 4 values:  165.33333333333334
Mean val from 4 values:  167.0
Mean val from 4 values:  162.77499999999998
Mean val from 4 values:  182.25
Mean val from 4 values:  162.66666666666666
Mean val from 4 values:  182.75
Mean val from 4 values:  189.075
Mean val from 4 values:  167.2
Mean val from 4 values:  158.55
Mean val from 4 values:  172.0
Mean val from 4 values:  167.0
Mean val from 4 values:  163.875
Mean val from 4 values:  163.375
Mean val from 4 values:  172.575
Mean val from 4 values:  172.5
Mean val from 4 values:  158.175
Mean val from 4 values:  159.725
Mean val from 4 values:  185.375
Mean val from 4 values:  177.675
Mean val from 4 values:  153.45
Mean val from 4 values:  180.525
Mean val from 4 values:  169.975
Mean val from 4 values:  161.1
Mean val from 4 values:  169.825
Mean val from 4 values:  152.775
Mean val from 4 values:  172.75
Mean val from 4 values:  170.0
Mean val from 4 values:  165.75
Mean val from 4 values:  166.9
Mean val from 4 values:  172.25
Mean val from 4 values:  174.025
Mean val from 4 values:  184.975
Mean val from 4 values:  156.5
Mean val from 4 values:  168.25
Mean val from 4 values:  186.5
Mean val from 4 values:  157.0
Mean val from 4 values:  176.75
Mean val from 4 values:  173.5
Mean val from 4 values:  168.0
Mean val from 4 values:  155.27499999999998
Mean val from 4 values:  166.25
Mean val from 4 values:  182.67499999999998
Mean val from 4 values:  166.3
Mean val from 4 values:  166.125
Mean val from 4 values:  171.425
Mean val from 4 values:  176.8
Mean val from 4 values:  164.175
Mean val from 4 values:  196.3
Mean val from 4 values:  160.925
Mean val from 4 values:  189.05
Mean val from 4 values:  160.15
Mean val from 4 values:  158.8
Mean val from 4 values:  165.1
Mean val from 4 values:  164.15
Mean val from 4 values:  192.25
Mean val from 4 values:  170.07500000000002
Mean val from 4 values:  181.125
Mean val from 4 values:  172.15
Mean val from 4 values:  166.25
Mean val from 4 values:  166.9
Mean val from 4 values:  172.0

,CGM,id,bolus,basal,insulin_type,age,gender,weight,height
date,,,,,,,,,
2019-02-08 14:05:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:10:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:15:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:20:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:25:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8

### Save Resampled Data

In [26]:
df_final

,CGM,id,bolus,basal,insulin_type,age,gender,weight,height
date,,,,,,,,,
2019-02-08 14:05:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:10:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:15:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:20:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
2019-02-08 14:25:00,NaN,26,NaN,1.15,Novolog (Aspart),18.0,F,82.8,163.8
...,...,...,...,...,...,...,...,...,...
2019-07-26 08:00:00,171.0,113,0.15,0.00,Humalog (Lispro),17.0,F,72.8,172.0
2019-07-26 08:05:00,180.0,113,0.45,0.00,Humalog (Lispro),17.0,F,72.8,172.0
2019-07-26 08:10:00,185.0,113,0.13,0.00,Humalog (Lispro),17.0,F,72.8,172.0
2019-07-26 08:15:00,187.0,113,0.15,0.00,Humalog (Lispro),17.0,F,72.8,172.0
2019-07-26 08:20:00,182.0,113,0.15,0.00,Humalog (Lispro),17.0,F,72.8,172.0

In [27]:
save_file_path = "../../data/resampled/"
os.makedirs(save_file_path, exist_ok=True)
df_final.to_csv(save_file_path + 'Flair.csv')