# Resampling of Loop Study Public Dataset

In [4]:
import os
import numpy as np
import pandas as pd
from datetime import datetime

### Read Existing Tables

In [63]:
file_path = "../../data/out/Loop study public dataset 2023-01-31/"
file_map = {
    'cgm': 'Loop_cgm_history.csv.gz',
    'bolus': 'Loop_bolus_event_history.csv.gz',
    'basal': 'Loop_basal_event_history.csv.gz',
}

In [99]:
def get_df_from_file(file_path, file_name, parse_datetime=True, sep=',', encoding='utf-8'):
    df = pd.read_csv(file_path + file_name, sep=sep, on_bad_lines='skip', encoding=encoding)
    if parse_datetime:
        df['date'] = pd.to_datetime(df['datetime'], unit='s')
    return df

In [65]:
def get_extended_df(original_df, value_column):
    """
    Get a df where quantities are distributed throughout 5-minute intervals instead of having start- and end dates.
    """
    new_rows = []
    for _, row in original_df.iterrows():
        new_rows.extend(split_duration(row, value_column))
    extended_df = pd.DataFrame(new_rows)
    extended_df.set_index('date', inplace=True)
    return extended_df

def split_duration(row, value_column):
    """
    For features with a duration, we split the values across 5-minute intervals by adding
    new rows for every 5-minute window in duration, and equally split the original quantity across those rows.
    """
    duration = row['end_date'] - row['date']
    rounded_duration = round(duration / pd.Timedelta(minutes=5)) * pd.Timedelta(minutes=5)
    num_intervals = rounded_duration // pd.Timedelta(minutes=5)
    if num_intervals < 1:
        num_intervals = 1
    value_per_interval = row[value_column] / num_intervals
    new_rows = []
    for i in range(int(num_intervals)):
        new_row = {
            'date': row['date'] + pd.Timedelta(minutes=5 * i),
            value_column: value_per_interval,
            'patient_id': row['patient_id'],
        }
        new_rows.append(new_row)
    return new_rows

In [66]:
df_glucose = get_df_from_file(file_path, file_map['cgm'])
df_bolus = get_df_from_file(file_path, file_map['bolus'])
df_basal = get_df_from_file(file_path, file_map['basal'])

### Resample Existing Tables

In [67]:
df_glucose.set_index('date', inplace=True)
df_glucose.head()

                       datetime  cgm  patient_id
date
2018-06-15 19:01:43  1529089303  396           3
2018-06-15 19:06:44  1529089604  394           3
2018-06-15 19:11:44  1529089904  387           3
2018-06-15 19:21:44  1529090504  338           3
2018-06-15 19:26:48  1529090808  331           3

In [68]:
df_bolus_orig = df_bolus.copy()
df_bolus['end_date'] = df_bolus['date'] + pd.to_timedelta(df_bolus['delivery_duration'], unit='s')
df_bolus = get_extended_df(df_bolus, 'bolus')
df_bolus

                     bolus  patient_id
date
2017-10-20 10:38:25   2.70         960
2017-10-20 17:00:39   3.40         960
2017-10-20 20:09:03   3.50         960
2017-10-21 08:36:23   0.90         960
2017-10-21 09:42:10   1.70         960
...                    ...         ...
2020-03-29 16:28:13   1.65         642
2020-03-29 17:24:23   1.30         642
2020-03-29 19:00:46   0.50         642
2020-03-29 19:32:58   0.75         642
2020-03-29 20:34:44   1.05         642

[2576100 rows x 2 columns]

In [69]:
print(f'New sum after distribution of extended boluses: {df_bolus["bolus"].sum():.2f}, should be: {df_bolus_orig["bolus"].sum():.2f}')

New sum after distribution of extended boluses: 4668918.42, should be: 4668918.42

In [70]:
df_basal_orig = df_basal.copy()
df_basal.sort_values(by=['patient_id', 'date'], inplace=True)
df_basal.set_index('date', inplace=True)
df_basal

                     patient_id    datetime  basal_rate
date
2018-09-08 16:16:47           3  1536423407       0.410
2018-09-08 17:30:00           3  1536427800       0.467
2018-09-08 19:00:00           3  1536433200       0.550
2018-09-08 21:00:00           3  1536440400       0.500
2018-09-08 23:00:00           3  1536447600       0.333
...                         ...         ...         ...
2018-11-28 18:01:22        1212  1543428082       3.399
2018-11-28 18:02:15        1212  1543428135       3.790
2018-11-28 18:06:13        1212  1543428373       4.040
2018-11-28 18:31:28        1212  1543429888       0.000
2018-11-28 18:55:59        1212  1543431359       0.000

[48080493 rows x 3 columns]

In [71]:
processed_dfs = []
subject_ids = df_glucose['patient_id'].unique()
print("Subjects:", len(subject_ids))
for subject_id in subject_ids:
    df_subject = df_glucose[df_glucose['patient_id'] == subject_id].copy()
    df_subject = df_subject[['cgm']].resample('5min', label='right').mean()
    df_subject['patient_id'] = subject_id
    df_subject.sort_index(inplace=True)

    def merge_data(df_col, df_subject, col_names, subject_id, agg_type='sum'):
        """ agg_type is data aggregation type. """
        df_subset = df_col[df_col['patient_id'] == subject_id].copy()
        if not df_subset.empty:
            if agg_type == 'mean':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').mean()
            elif agg_type == 'sum':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').sum()
            elif agg_type == 'first':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').first()
            elif agg_type == 'last':
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').last()
            else:
                df_subset = df_subset[df_subset[col_names].notna()][col_names].resample('5min', label='right').sum()
            df_subject = pd.merge(df_subject, df_subset, on="date", how='outer')
        else:
            df_subject[col_names] = np.nan
        return df_subject

    # Add insulin and insulin type
    df_subject = merge_data(df_bolus, df_subject, ['bolus'], subject_id, agg_type='sum')
    df_subject = merge_data(df_basal, df_subject, ['basal_rate'], subject_id, agg_type='last')
    df_subject['basal_rate'] = df_subject['basal_rate'].ffill()
    
    df_subject['patient_id'] = subject_id
    df_subject = df_subject.rename(columns={'patient_id': 'id', 'basal_rate': 'basal', 'cgm': 'CGM'})
    processed_dfs.append(df_subject)
    print(f"{subject_id} is finished processing")

df_final = pd.concat(processed_dfs)

Subjects: 851
3 is finished processing
4 is finished processing
5 is finished processing
6 is finished processing
7 is finished processing
9 is finished processing
10 is finished processing
11 is finished processing
12 is finished processing
13 is finished processing
15 is finished processing
16 is finished processing
18 is finished processing
19 is finished processing
20 is finished processing
21 is finished processing
24 is finished processing
25 is finished processing
26 is finished processing
27 is finished processing
30 is finished processing
32 is finished processing
33 is finished processing
34 is finished processing
38 is finished processing
41 is finished processing
43 is finished processing
44 is finished processing
45 is finished processing
46 is finished processing
47 is finished processing
50 is finished processing
52 is finished processing
53 is finished processing
55 is finished processing
57 is finished processing
59 is finished processing
60 is finished processing
62 is finished processing
63 is finished processing
66 is finished processing
67 is finished processing
68 is finished processing
69 is finished processing
70 is finished processing
71 is finished processing
73 is finished processing
74 is finished processing
75 is finished processing
76 is finished processing
78 is finished processing
79 is finished processing
81 is finished processing
82 is finished processing
84 is finished processing
85 is finished processing
86 is finished processing
88 is finished processing
90 is finished processing
91 is finished processing
92 is finished processing
93 is finished processing
95 is finished processing
96 is finished processing
97 is finished processing
98 is finished processing
99 is finished processing
100 is finished processing
101 is finished processing
102 is finished processing
104 is finished processing
105 is finished processing
106 is finished processing
107 is finished processing
110 is finished processing
112 is finished processing
113 is finished processing
114 is finished processing
115 is finished processing
116 is finished processing
119 is finished processing
120 is finished processing
121 is finished processing
124 is finished processing
125 is finished processing
128 is finished processing
129 is finished processing
130 is finished processing
131 is finished processing
133 is finished processing
134 is finished processing
137 is finished processing
138 is finished processing
139 is finished processing
141 is finished processing
142 is finished processing
143 is finished processing
145 is finished processing
146 is finished processing
148 is finished processing
149 is finished processing
150 is finished processing
151 is finished processing
153 is finished processing
154 is finished processing
155 is finished processing
156 is finished processing
157 is finished processing
158 is finished processing
160 is finished processing
162 is finished processing
163 is finished processing
164 is finished processing
165 is finished processing
167 is finished processing
169 is finished processing
171 is finished processing
173 is finished processing
175 is finished processing
176 is finished processing
178 is finished processing
179 is finished processing
181 is finished processing
183 is finished processing
184 is finished processing
185 is finished processing
186 is finished processing
188 is finished processing
189 is finished processing
190 is finished processing
191 is finished processing
193 is finished processing
194 is finished processing
195 is finished processing
198 is finished processing
200 is finished processing
201 is finished processing
202 is finished processing
203 is finished processing
204 is finished processing
205 is finished processing
206 is finished processing
207 is finished processing
208 is finished processing
209 is finished processing
212 is finished processing
213 is finished processing
214 is finished processing
215 is finished processing
216 is finished processing
217 is finished processing
219 is finished processing
221 is finished processing
222 is finished processing
223 is finished processing
224 is finished processing
227 is finished processing
228 is finished processing
230 is finished processing
231 is finished processing
232 is finished processing
234 is finished processing
235 is finished processing
236 is finished processing
237 is finished processing
238 is finished processing
239 is finished processing
240 is finished processing
241 is finished processing
242 is finished processing
244 is finished processing
245 is finished processing
246 is finished processing
247 is finished processing
248 is finished processing
249 is finished processing
250 is finished processing
251 is finished processing
252 is finished processing
254 is finished processing
255 is finished processing
256 is finished processing
258 is finished processing
260 is finished processing
262 is finished processing
263 is finished processing
264 is finished processing
266 is finished processing
267 is finished processing
268 is finished processing
269 is finished processing
270 is finished processing
271 is finished processing
272 is finished processing
273 is finished processing
274 is finished processing
277 is finished processing
278 is finished processing
280 is finished processing
281 is finished processing
282 is finished processing
283 is finished processing
284 is finished processing
291 is finished processing
292 is finished processing
293 is finished processing
295 is finished processing
296 is finished processing
297 is finished processing
299 is finished processing
300 is finished processing
301 is finished processing
302 is finished processing
303 is finished processing
304 is finished processing
306 is finished processing
307 is finished processing
310 is finished processing
311 is finished processing
312 is finished processing
314 is finished processing
316 is finished processing
317 is finished processing
319 is finished processing
320 is finished processing
321 is finished processing
324 is finished processing
326 is finished processing
327 is finished processing
329 is finished processing
330 is finished processing
332 is finished processing
333 is finished processing
335 is finished processing
336 is finished processing
337 is finished processing
338 is finished processing
339 is finished processing
340 is finished processing
341 is finished processing
342 is finished processing
343 is finished processing
346 is finished processing
347 is finished processing
349 is finished processing
352 is finished processing
353 is finished processing
355 is finished processing
356 is finished processing
358 is finished processing
359 is finished processing
360 is finished processing
361 is finished processing
363 is finished processing
364 is finished processing
365 is finished processing
366 is finished processing
369 is finished processing
375 is finished processing
376 is finished processing
379 is finished processing
380 is finished processing
381 is finished processing
382 is finished processing
383 is finished processing
384 is finished processing
385 is finished processing
386 is finished processing
387 is finished processing
388 is finished processing
389 is finished processing
390 is finished processing
393 is finished processing
394 is finished processing
395 is finished processing
396 is finished processing
399 is finished processing
400 is finished processing
401 is finished processing
402 is finished processing
404 is finished processing
405 is finished processing
406 is finished processing
407 is finished processing
408 is finished processing
409 is finished processing
410 is finished processing
413 is finished processing
414 is finished processing
415 is finished processing
416 is finished processing
417 is finished processing
419 is finished processing
420 is finished processing
423 is finished processing
425 is finished processing
427 is finished processing
428 is finished processing
430 is finished processing
431 is finished processing
432 is finished processing
433 is finished processing
434 is finished processing
435 is finished processing
436 is finished processing
437 is finished processing
438 is finished processing
439 is finished processing
441 is finished processing
442 is finished processing
443 is finished processing
445 is finished processing
446 is finished processing
447 is finished processing
448 is finished processing
449 is finished processing
450 is finished processing
451 is finished processing
452 is finished processing
453 is finished processing
454 is finished processing
455 is finished processing
456 is finished processing
457 is finished processing
458 is finished processing
459 is finished processing
460 is finished processing
461 is finished processing
462 is finished processing
463 is finished processing
464 is finished processing
466 is finished processing
467 is finished processing
468 is finished processing
470 is finished processing
471 is finished processing
473 is finished processing
476 is finished processing
477 is finished processing
481 is finished processing
482 is finished processing
484 is finished processing
487 is finished processing
488 is finished processing
489 is finished processing
493 is finished processing
495 is finished processing
496 is finished processing
497 is finished processing
498 is finished processing
500 is finished processing
503 is finished processing
504 is finished processing
505 is finished processing
508 is finished processing
510 is finished processing
511 is finished processing
513 is finished processing
515 is finished processing
516 is finished processing
520 is finished processing
521 is finished processing
522 is finished processing
524 is finished processing
525 is finished processing
527 is finished processing
528 is finished processing
530 is finished processing
532 is finished processing
533 is finished processing
535 is finished processing
536 is finished processing
537 is finished processing
538 is finished processing
539 is finished processing
540 is finished processing
542 is finished processing
543 is finished processing
545 is finished processing
546 is finished processing
548 is finished processing
549 is finished processing
550 is finished processing
551 is finished processing
552 is finished processing
554 is finished processing
556 is finished processing
559 is finished processing
561 is finished processing
565 is finished processing
568 is finished processing
569 is finished processing
570 is finished processing
571 is finished processing
572 is finished processing
573 is finished processing
574 is finished processing
577 is finished processing
578 is finished processing
580 is finished processing
582 is finished processing
583 is finished processing
584 is finished processing
585 is finished processing
587 is finished processing
588 is finished processing
589 is finished processing
590 is finished processing
592 is finished processing
594 is finished processing
596 is finished processing
597 is finished processing
598 is finished processing
599 is finished processing
602 is finished processing
605 is finished processing
606 is finished processing
607 is finished processing
609 is finished processing
610 is finished processing
611 is finished processing
613 is finished processing
615 is finished processing
616 is finished processing
617 is finished processing
620 is finished processing
621 is finished processing
623 is finished processing
625 is finished processing
626 is finished processing
627 is finished processing
629 is finished processing
630 is finished processing
632 is finished processing
633 is finished processing
634 is finished processing
635 is finished processing
636 is finished processing
637 is finished processing
638 is finished processing
639 is finished processing
641 is finished processing
642 is finished processing
644 is finished processing
645 is finished processing
646 is finished processing
647 is finished processing
650 is finished processing
651 is finished processing
653 is finished processing
654 is finished processing
657 is finished processing
659 is finished processing
660 is finished processing
663 is finished processing
664 is finished processing
665 is finished processing
666 is finished processing
668 is finished processing
669 is finished processing
672 is finished processing
675 is finished processing
676 is finished processing
677 is finished processing
679 is finished processing
680 is finished processing
681 is finished processing
682 is finished processing
683 is finished processing
684 is finished processing
685 is finished processing
686 is finished processing
687 is finished processing
688 is finished processing
689 is finished processing
691 is finished processing
692 is finished processing
693 is finished processing
695 is finished processing
696 is finished processing
697 is finished processing
699 is finished processing
700 is finished processing
701 is finished processing
702 is finished processing
703 is finished processing
705 is finished processing
710 is finished processing
711 is finished processing
712 is finished processing
713 is finished processing
716 is finished processing
718 is finished processing
722 is finished processing
723 is finished processing
724 is finished processing
725 is finished processing
726 is finished processing
727 is finished processing
728 is finished processing
729 is finished processing
730 is finished processing
732 is finished processing
733 is finished processing
736 is finished processing
738 is finished processing
739 is finished processing
740 is finished processing
741 is finished processing
742 is finished processing
743 is finished processing
745 is finished processing
747 is finished processing
750 is finished processing
751 is finished processing
752 is finished processing
753 is finished processing
754 is finished processing
755 is finished processing
756 is finished processing
758 is finished processing
759 is finished processing
760 is finished processing
763 is finished processing
764 is finished processing
765 is finished processing
766 is finished processing
767 is finished processing
769 is finished processing
770 is finished processing
772 is finished processing
773 is finished processing
774 is finished processing
775 is finished processing
776 is finished processing
778 is finished processing
779 is finished processing
780 is finished processing
784 is finished processing
785 is finished processing
787 is finished processing
788 is finished processing
790 is finished processing
791 is finished processing
792 is finished processing
793 is finished processing
794 is finished processing
795 is finished processing
796 is finished processing
797 is finished processing
798 is finished processing
799 is finished processing
800 is finished processing
801 is finished processing
803 is finished processing
805 is finished processing
806 is finished processing
807 is finished processing
810 is finished processing
814 is finished processing
815 is finished processing
816 is finished processing
819 is finished processing
821 is finished processing
823 is finished processing
824 is finished processing
826 is finished processing
829 is finished processing
831 is finished processing
833 is finished processing
834 is finished processing
835 is finished processing
841 is finished processing
842 is finished processing
843 is finished processing
844 is finished processing
845 is finished processing
847 is finished processing
848 is finished processing
850 is finished processing
851 is finished processing
852 is finished processing
853 is finished processing
854 is finished processing
856 is finished processing
858 is finished processing
859 is finished processing
862 is finished processing
863 is finished processing
867 is finished processing
870 is finished processing
874 is finished processing
877 is finished processing
878 is finished processing
879 is finished processing
880 is finished processing
881 is finished processing
883 is finished processing
884 is finished processing
887 is finished processing
888 is finished processing
889 is finished processing
891 is finished processing
892 is finished processing
893 is finished processing
895 is finished processing
897 is finished processing
899 is finished processing
900 is finished processing
902 is finished processing
903 is finished processing
904 is finished processing
905 is finished processing
907 is finished processing
908 is finished processing
909 is finished processing
910 is finished processing
911 is finished processing
913 is finished processing
914 is finished processing
916 is finished processing
917 is finished processing
918 is finished processing
919 is finished processing
920 is finished processing
921 is finished processing
923 is finished processing
925 is finished processing
926 is finished processing
927 is finished processing
928 is finished processing
929 is finished processing
930 is finished processing
931 is finished processing
932 is finished processing
934 is finished processing
935 is finished processing
936 is finished processing
937 is finished processing
939 is finished processing
941 is finished processing
942 is finished processing
943 is finished processing
944 is finished processing
946 is finished processing
947 is finished processing
949 is finished processing
953 is finished processing
954 is finished processing
956 is finished processing
957 is finished processing
958 is finished processing
960 is finished processing
961 is finished processing
962 is finished processing
963 is finished processing
967 is finished processing
968 is finished processing
969 is finished processing
970 is finished processing
971 is finished processing
972 is finished processing
973 is finished processing
974 is finished processing
975 is finished processing
976 is finished processing
977 is finished processing
978 is finished processing
979 is finished processing
980 is finished processing
981 is finished processing
982 is finished processing
983 is finished processing
984 is finished processing
986 is finished processing
987 is finished processing
988 is finished processing
989 is finished processing
992 is finished processing
993 is finished processing
995 is finished processing
996 is finished processing
997 is finished processing
998 is finished processing
999 is finished processing
1000 is finished processing
1001 is finished processing
1002 is finished processing
1004 is finished processing
1005 is finished processing
1008 is finished processing
1009 is finished processing
1011 is finished processing
1012 is finished processing
1013 is finished processing
1014 is finished processing
1016 is finished processing
1017 is finished processing
1018 is finished processing
1019 is finished processing
1021 is finished processing
1023 is finished processing
1025 is finished processing
1026 is finished processing
1027 is finished processing
1029 is finished processing
1030 is finished processing
1031 is finished processing
1033 is finished processing
1036 is finished processing
1037 is finished processing
1039 is finished processing
1041 is finished processing
1042 is finished processing
1043 is finished processing
1044 is finished processing
1045 is finished processing
1046 is finished processing
1047 is finished processing
1048 is finished processing
1049 is finished processing
1052 is finished processing
1053 is finished processing
1054 is finished processing
1055 is finished processing
1056 is finished processing
1057 is finished processing
1058 is finished processing
1059 is finished processing
1060 is finished processing
1061 is finished processing
1062 is finished processing
1063 is finished processing
1064 is finished processing
1065 is finished processing
1066 is finished processing
1067 is finished processing
1068 is finished processing
1069 is finished processing
1070 is finished processing

In [72]:
df_final

                       CGM    id  bolus  basal
date
2018-06-15 19:05:00  396.0     3    NaN    NaN
2018-06-15 19:10:00  394.0     3    NaN    NaN
2018-06-15 19:15:00  387.0     3    NaN    NaN
2018-06-15 19:20:00    NaN     3    NaN    NaN
2018-06-15 19:25:00  338.0     3    NaN    NaN
...                    ...   ...    ...    ...
2018-11-28 18:40:00  141.0  1212    NaN    0.0
2018-11-28 18:45:00  128.0  1212    NaN    0.0
2018-11-28 18:50:00  125.0  1212    NaN    0.0
2018-11-28 18:55:00  127.0  1212    NaN    0.0
2018-11-28 19:00:00  135.0  1212    NaN    0.0

[95061066 rows x 4 columns]

### Add Additional Tables

We found:
- Carbs
- Exercise
- Insulin type
- Age
- Weight
- Height
- Gender

In [73]:
raw_data_file_path = "../../data/raw/Loop study public dataset 2023-01-31/Data Tables/"

In [74]:
# Get time zone shift for subjects
df_time_zone = get_df_from_file(raw_data_file_path, 'PtRoster.txt', parse_datetime=False, sep='|')
df_time_zone = df_time_zone[['PtID', 'PtTimezoneOffset']]
df_time_zone = df_time_zone.rename(columns={'PtID': 'id', 'PtTimezoneOffset': 'tz_offset'})
df_time_zone

       id  tz_offset
0     963       -8.0
1      55       -8.0
2    1082       -5.0
3    1173       -8.0
4     296       -8.0
..    ...        ...
914   913       -5.0
915   459       -6.0
916   409       -5.0
917   854       -5.0
918   329       -8.0

[919 rows x 2 columns]

In [75]:
# No duplicate ids in this df
df_time_zone[df_time_zone.duplicated('id', keep=False)].sort_values(by=['id'])

Empty DataFrame
Columns: [id, tz_offset]
Index: []

In [76]:
def get_df_with_local_date(df, utc_date_col, df_time_zone):
    processed_dfs = []
    subject_ids = df['id'].unique()
    print("Subjects:", len(subject_ids))
    for subject_id in subject_ids:
        df_subject = df[df['id'] == subject_id].copy()
        df_tz_subject = df_time_zone[df_time_zone['id'] == subject_id].copy()
        if not df_tz_subject.empty:
            subject_dt_offset = df_tz_subject['tz_offset'].iloc[0]
        else:
            subject_dt_offset = 0
        df_subject['date'] = df_subject[utc_date_col] + pd.to_timedelta(subject_dt_offset, unit='hour')
        processed_dfs.append(df_subject)
        print(f"{subject_id} is finished processing")
    return pd.concat(processed_dfs)

In [77]:
# Adding carbs
df_carbs = get_df_from_file(raw_data_file_path, 'LOOPDeviceFood.txt', parse_datetime=False, sep='|')
df_carbs = df_carbs.rename(columns={'PtID': 'id'})
df_carbs['UTCDtTm'] = pd.to_datetime(df_carbs['UTCDtTm'])
df_carbs = get_df_with_local_date(df_carbs, 'UTCDtTm', df_time_zone)
df_carbs[['id', 'UTCDtTm', 'date', 'CarbsNet']].head()

/var/folders/q1/5jqy1fgs07j9ptpmdsmmhxnw0000gn/T/ipykernel_93979/2272110270.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path + file_name, sep=sep)

Subjects: 837
1082 is finished processing
1173 is finished processing
296 is finished processing
1152 is finished processing
1013 is finished processing
829 is finished processing
104 is finished processing
942 is finished processing
105 is finished processing
960 is finished processing
467 is finished processing
458 is finished processing
589 is finished processing
407 is finished processing
856 is finished processing
605 is finished processing
738 is finished processing
787 is finished processing
691 is finished processing
763 is finished processing
653 is finished processing
511 is finished processing
85 is finished processing
164 is finished processing
425 is finished processing
213 is finished processing
1080 is finished processing
153 is finished processing
621 is finished processing
462 is finished processing
543 is finished processing
607 is finished processing
826 is finished processing
67 is finished processing
961 is finished processing
970 is finished processing
456 is finished processing
920 is finished processing
936 is finished processing
1079 is finished processing
1081 is finished processing
968 is finished processing
1138 is finished processing
125 is finished processing
644 is finished processing
859 is finished processing
650 is finished processing
587 is finished processing
212 is finished processing
9 is finished processing
101 is finished processing
963 is finished processing
834 is finished processing
242 is finished processing
224 is finished processing
1140 is finished processing
388 is finished processing
84 is finished processing
432 is finished processing
508 is finished processing
634 is finished processing
1158 is finished processing
1093 is finished processing
533 is finished processing
251 is finished processing
438 is finished processing
998 is finished processing
295 is finished processing
932 is finished processing
216 is finished processing
1067 is finished processing
1211 is finished processing
231 is finished processing
1004 is finished processing
312 is finished processing
1105 is finished processing
55 is finished processing
130 is finished processing
851 is finished processing
417 is finished processing
1204 is finished processing
96 is finished processing
420 is finished processing
743 is finished processing
1107 is finished processing
292 is finished processing
745 is finished processing
396 is finished processing
867 is finished processing
179 is finished processing
884 is finished processing
570 is finished processing
957 is finished processing
977 is finished processing
32 is finished processing
303 is finished processing
1123 is finished processing
641 is finished processing
236 is finished processing
773 is finished processing
807 is finished processing
75 is finished processing
916 is finished processing
908 is finished processing
627 is finished processing
699 is finished processing
741 is finished processing
982 is finished processing
504 is finished processing
833 is finished processing
617 is finished processing
852 is finished processing
819 is finished processing
102 is finished processing
470 is finished processing
1008 is finished processing
228 is finished processing
1181 is finished processing
167 is finished processing
19 is finished processing
353 is finished processing
892 is finished processing
535 is finished processing
797 is finished processing
767 is finished processing
227 is finished processing
903 is finished processing
1036 is finished processing
450 is finished processing
34 is finished processing
457 is finished processing
793 is finished processing
12 is finished processing
949 is finished processing
98 is finished processing
1206 is finished processing
759 is finished processing
766 is finished processing
958 is finished processing
267 is finished processing
1199 is finished processing
1103 is finished processing
944 is finished processing
1187 is finished processing
282 is finished processing
510 is finished processing
495 is finished processing
1147 is finished processing
399 is finished processing
13 is finished processing
60 is finished processing
389 is finished processing
973 is finished processing
1162 is finished processing
120 is finished processing
69 is finished processing
361 is finished processing
636 is finished processing
992 is finished processing
245 is finished processing
669 is finished processing
1099 is finished processing
663 is finished processing
755 is finished processing
680 is finished processing
340 is finished processing
247 is finished processing
1011 is finished processing
524 is finished processing
319 is finished processing
346 is finished processing
1163 is finished processing
842 is finished processing
941 is finished processing
445 is finished processing
1150 is finished processing
683 is finished processing
701 is finished processing
1048 is finished processing
1169 is finished processing
1155 is finished processing
1210 is finished processing
41 is finished processing
116 is finished processing
888 is finished processing
1143 is finished processing
679 is finished processing
907 is finished processing
484 is finished processing
590 is finished processing
66 is finished processing
1190 is finished processing
1061 is finished processing
202 is finished processing
928 is finished processing
201 is finished processing
967 is finished processing
800 is finished processing
923 is finished processing
637 is finished processing
405 is finished processing
11 is finished processing
93 is finished processing
1059 is finished processing
981 is finished processing
1044 is finished processing
779 is finished processing
428 is finished processing
205 is finished processing
538 is finished processing
794 is finished processing
646 is finished processing
626 is finished processing
921 is finished processing
870 is finished processing
688 is finished processing
5 is finished processing
92 is finished processing
1052 is finished processing
1054 is finished processing
711 is finished processing
158 is finished processing
540 is finished processing
1017 is finished processing
190 is finished processing
284 is finished processing
366 is finished processing
1009 is finished processing
1108 is finished processing
415 is finished processing
756 is finished processing
909 is finished processing
355 is finished processing
145 is finished processing
571 is finished processing
71 is finished processing
758 is finished processing
44 is finished processing
692 is finished processing
585 is finished processing
191 is finished processing
365 is finished processing
207 is finished processing
693 is finished processing
302 is finished processing
596 is finished processing
647 is finished processing
835 is finished processing
821 is finished processing
676 is finished processing
705 is finished processing
677 is finished processing
1071 is finished processing
969 is finished processing
503 is finished processing
727 is finished processing
939 is finished processing
271 is finished processing
665 is finished processing
1000 is finished processing
1122 is finished processing
983 is finished processing
1137 is finished processing
660 is finished processing
193 is finished processing
525 is finished processing
452 is finished processing
380 is finished processing
95 is finished processing
278 is finished processing
878 is finished processing
33 is finished processing
747 is finished processing
597 is finished processing
297 is finished processing
476 is finished processing
1095 is finished processing
863 is finished processing
542 is finished processing
1018 is finished processing
82 is finished processing
335 is finished processing
947 is finished processing
260 is finished processing
106 is finished processing
435 is finished processing
657 is finished processing
1086 is finished processing
931 is finished processing
999 is finished processing
1176 is finished processing
189 is finished processing
63 is finished processing
449 is finished processing
1057 is finished processing
841 is finished processing
186 is finished processing
281 is finished processing
1125 is finished processing
262 is finished processing
986 is finished processing
532 is finished processing
1148 is finished processing
1085 is finished processing
464 is finished processing
724 is finished processing
250 is finished processing
975 is finished processing
805 is finished processing
358 is finished processing
142 is finished processing
1132 is finished processing
606 is finished processing
343 is finished processing
610 is finished processing
1065 is finished processing
27 is finished processing
430 is finished processing
980 is finished processing
784 is finished processing
133 is finished processing
73 is finished processing
176 is finished processing
337 is finished processing
363 is finished processing
796 is finished processing
1165 is finished processing
844 is finished processing
620 is finished processing
623 is finished processing
536 is finished processing
769 is finished processing
1097 is finished processing
899 is finished processing
993 is finished processing
91 is finished processing
1114 is finished processing
291 is finished processing
138 is finished processing
43 is finished processing
1039 is finished processing
1002 is finished processing
157 is finished processing
162 is finished processing
1112 is finished processing
552 is finished processing
905 is finished processing
76 is finished processing
774 is finished processing
1202 is finished processing
195 is finished processing
327 is finished processing
1053 is finished processing
1116 is finished processing
823 is finished processing
379 is finished processing
248 is finished processing
880 is finished processing
384 is finished processing
843 is finished processing
141 is finished processing
175 is finished processing
489 is finished processing
336 is finished processing
30 is finished processing
572 is finished processing
751 is finished processing
155 is finished processing
1043 is finished processing
453 is finished processing
1041 is finished processing
725 is finished processing
46 is finished processing
989 is finished processing
53 is finished processing
38 is finished processing
110 is finished processing
798 is finished processing
137 is finished processing
651 is finished processing
668 is finished processing
352 is finished processing
799 is finished processing
824 is finished processing
550 is finished processing
381 is finished processing
639 is finished processing
1062 is finished processing
266 is finished processing
1005 is finished processing
316 is finished processing
235 is finished processing
188 is finished processing
858 is finished processing
338 is finished processing
1026 is finished processing
926 is finished processing
946 is finished processing
349 is finished processing
1066 is finished processing
1141 is finished processing
163 is finished processing
1055 is finished processing
726 is finished processing
527 is finished processing
918 is finished processing
1089 is finished processing
635 is finished processing
716 is finished processing
181 is finished processing
149 is finished processing
214 is finished processing
50 is finished processing
891 is finished processing
482 is finished processing
874 is finished processing
88 is finished processing
515 is finished processing
321 is finished processing
1126 is finished processing
320 is finished processing
497 is finished processing
209 is finished processing
24 is finished processing
427 is finished processing
448 is finished processing
546 is finished processing
1195 is finished processing
925 is finished processing
687 is finished processing
1133 is finished processing
270 is finished processing
463 is finished processing
237 is finished processing
128 is finished processing
730 is finished processing
1142 is finished processing
1090 is finished processing
710 is finished processing
404 is finished processing
99 is finished processing
752 is finished processing
6 is finished processing
342 is finished processing
664 is finished processing
477 is finished processing
632 is finished processing
551 is finished processing
498 is finished processing
86 is finished processing
442 is finished processing
239 is finished processing
814 is finished processing
173 is finished processing
1127 is finished processing
25 is finished processing
521 is finished processing
742 is finished processing
493 is finished processing
1109 is finished processing
488 is finished processing
578 is finished processing
616 is finished processing
1153 is finished processing
148 is finished processing
15 is finished processing
258 is finished processing
914 is finished processing
324 is finished processing
446 is finished processing
26 is finished processing
1209 is finished processing
238 is finished processing
184 is finished processing
473 is finished processing
893 is finished processing
234 is finished processing
1196 is finished processing
97 is finished processing
119 is finished processing
1058 is finished processing
1172 is finished processing
500 is finished processing
723 is finished processing
171 is finished processing
568 is finished processing
364 is finished processing
3 is finished processing
537 is finished processing
943 is finished processing
1177 is finished processing
695 is finished processing
810 is finished processing
910 is finished processing
1171 is finished processing
879 is finished processing
256 is finished processing
732 is finished processing
801 is finished processing
1091 is finished processing
1033 is finished processing
1068 is finished processing
139 is finished processing
390 is finished processing
972 is finished processing
394 is finished processing
1167 is finished processing
684 is finished processing
299 is finished processing
654 is finished processing
1183 is finished processing
244 is finished processing
264 is finished processing
897 is finished processing
20 is finished processing
1118 is finished processing
1159 is finished processing
522 is finished processing
881 is finished processing
107 is finished processing
1117 is finished processing
900 is finished processing
272 is finished processing
775 is finished processing
395 is finished processing
718 is finished processing
549 is finished processing
481 is finished processing
62 is finished processing
183 is finished processing
300 is finished processing
599 is finished processing
772 is finished processing
4 is finished processing
447 is finished processing
151 is finished processing
217 is finished processing
577 is finished processing
722 is finished processing
471 is finished processing
10 is finished processing
134 is finished processing
215 is finished processing
788 is finished processing
675 is finished processing
246 is finished processing
68 is finished processing
1129 is finished processing
70 is finished processing
341 is finished processing
1179 is finished processing
400 is finished processing
114 is finished processing
845 is finished processing
356 is finished processing
414 is finished processing
1207 is finished processing
1031 is finished processing
580 is finished processing
831 is finished processing
1135 is finished processing
927 is finished processing
666 is finished processing
979 is finished processing
81 is finished processing
1198 is finished processing
1188 is finished processing
712 is finished processing
277 is finished processing
333 is finished processing
1056 is finished processing
862 is finished processing
1012 is finished processing
598 is finished processing
1101 is finished processing
16 is finished processing
1161 is finished processing
633 is finished processing
700 is finished processing
401 is finished processing
806 is finished processing
776 is finished processing
611 is finished processing
1178 is finished processing
47 is finished processing
1023 is finished processing
1047 is finished processing
539 is finished processing
1151 is finished processing
629 is finished processing
1175 is finished processing
385 is finished processing
1145 is finished processing
487 is finished processing
1119 is finished processing
765 is finished processing
146 is finished processing
200 is finished processing
625 is finished processing
121 is finished processing
154 is finished processing
230 is finished processing
1021 is finished processing
1014 is finished processing
393 is finished processing
1170 is finished processing
1115 is finished processing
911 is finished processing
850 is finished processing
953 is finished processing
919 is finished processing
241 is finished processing
419 is finished processing
988 is finished processing
962 is finished processing
1063 is finished processing
1025 is finished processing
369 is finished processing
1201 is finished processing
630 is finished processing
1184 is finished processing
221 is finished processing
1070 is finished processing
198 is finished processing
496 is finished processing
301 is finished processing
785 is finished processing
443 is finished processing
376 is finished processing
1045 is finished processing
685 is finished processing
383 is finished processing
548 is finished processing
816 is finished processing
273 is finished processing
131 is finished processing
883 is finished processing
165 is finished processing
1016 is finished processing
433 is finished processing
530 is finished processing
100 is finished processing
877 is finished processing
439 is finished processing
1193 is finished processing
995 is finished processing
847 is finished processing
954 is finished processing
987 is finished processing
1120 is finished processing
1069 is finished processing
206 is finished processing
520 is finished processing
269 is finished processing
1124 is finished processing
240 is finished processing
729 is finished processing
937 is finished processing
1001 is finished processing
573 is finished processing
280 is finished processing
79 is finished processing
410 is finished processing
1019 is finished processing
317 is finished processing
750 is finished processing
431 is finished processing
1042 is finished processing
513 is finished processing
1094 is finished processing
113 is finished processing
451 is finished processing
283 is finished processing
569 is finished processing
795 is finished processing
468 is finished processing
326 is finished processing
143 is finished processing
934 is finished processing
1027 is finished processing
307 is finished processing
169 is finished processing
733 is finished processing
112 is finished processing
528 is finished processing
1029 is finished processing
306 is finished processing
974 is finished processing
1060 is finished processing
895 is finished processing
1084 is finished processing
889 is finished processing
314 is finished processing
697 is finished processing
1049 is finished processing
703 is finished processing
904 is finished processing
406 is finished processing
441 is finished processing
753 is finished processing
156 is finished processing
659 is finished processing
208 is finished processing
194 is finished processing
249 is finished processing
754 is finished processing
682 is finished processing
454 is finished processing
790 is finished processing
360 is finished processing
1154 is finished processing
505 is finished processing
185 is finished processing
59 is finished processing
1212 is finished processing
115 is finished processing
736 is finished processing
74 is finished processing
574 is finished processing
760 is finished processing
204 is finished processing
160 is finished processing
359 is finished processing
902 is finished processing
689 is finished processing
1092 is finished processing
1037 is finished processing
582 is finished processing
778 is finished processing
416 is finished processing
929 is finished processing
792 is finished processing
268 is finished processing
387 is finished processing
460 is finished processing
434 is finished processing
461 is finished processing

     id             UTCDtTm                date  CarbsNet
0  1082 2018-06-03 14:33:05 2018-06-03 09:33:05       5.0
1  1082 2018-06-03 14:00:23 2018-06-03 09:00:23      30.0
2  1082 2018-06-03 03:50:28 2018-06-02 22:50:28      25.0
3  1082 2018-06-03 00:10:57 2018-06-02 19:10:57      48.0
4  1082 2018-06-02 22:40:11 2018-06-02 17:40:11      30.0

In [78]:
df_carbs[['id', 'UTCDtTm', 'date', 'CarbsNet']]

           id             UTCDtTm                date  CarbsNet
0        1082 2018-06-03 14:33:05 2018-06-03 09:33:05       5.0
1        1082 2018-06-03 14:00:23 2018-06-03 09:00:23      30.0
2        1082 2018-06-03 03:50:28 2018-06-02 22:50:28      25.0
3        1082 2018-06-03 00:10:57 2018-06-02 19:10:57      48.0
4        1082 2018-06-02 22:40:11 2018-06-02 17:40:11      30.0
...       ...                 ...                 ...       ...
1004782    45 2019-03-18 12:32:27 2019-03-18 07:32:27      15.0
1004783    45 2019-03-18 01:56:25 2019-03-17 20:56:25      15.0
1004784    45 2019-03-17 19:07:40 2019-03-17 14:07:40      35.0
1352827   516 2019-04-24 02:33:18 2019-04-23 18:33:18       2.0
1352828   516 2019-04-16 19:55:33 2019-04-16 11:55:33       5.0

[1406204 rows x 4 columns]

In [79]:
df_time_zone[df_time_zone['id'] == 45]

     id  tz_offset
333  45       -5.0

In [80]:
# Local time zone shifts look like they are working as expected

In [81]:
# Unit is always in grams
df_carbs[df_carbs['CarbsNet'] > 0]['CarbUnits'].unique()

array(['grams'], dtype=object)

In [82]:
df_carbs = df_carbs[['id', 'date', 'CarbsNet']]
df_carbs = df_carbs.rename(columns={'CarbsNet': 'carbs'})
df_carbs = df_carbs[df_carbs['carbs'] > 0]
df_carbs

           id                date  carbs
0        1082 2018-06-03 09:33:05    5.0
1        1082 2018-06-03 09:00:23   30.0
2        1082 2018-06-02 22:50:28   25.0
3        1082 2018-06-02 19:10:57   48.0
4        1082 2018-06-02 17:40:11   30.0
...       ...                 ...    ...
1004782    45 2019-03-18 07:32:27   15.0
1004783    45 2019-03-17 20:56:25   15.0
1004784    45 2019-03-17 14:07:40   35.0
1352827   516 2019-04-23 18:33:18    2.0
1352828   516 2019-04-16 11:55:33    5.0

[1405777 rows x 3 columns]

In [83]:
# Add carbs to df final
processed_dfs = []
subject_ids = df_final['id'].unique()
print("Subjects:", len(subject_ids))
for subject_id in subject_ids:
    df_subject = df_final[df_final['id'] == subject_id].copy()
    df_subject.sort_index(inplace=True)

    # Add carbs
    df_subject_carbs = df_carbs[df_carbs['id'] == subject_id].copy()
    df_subject_carbs.set_index('date', inplace=True)
    df_subject_carbs = df_subject_carbs[df_subject_carbs['carbs'].notna()]['carbs'].resample('5min', label='right').sum()
    df_subject = pd.merge(df_subject, df_subject_carbs, on="date", how='outer')
    
    df_subject['id'] = subject_id
    processed_dfs.append(df_subject)
    print(f"{subject_id} is finished processing")

df_final = pd.concat(processed_dfs)
df_final

Subjects: 851
3 is finished processing
4 is finished processing
5 is finished processing
6 is finished processing
7 is finished processing
9 is finished processing
10 is finished processing
11 is finished processing
12 is finished processing
13 is finished processing
15 is finished processing
16 is finished processing
18 is finished processing
19 is finished processing
20 is finished processing
21 is finished processing
24 is finished processing
25 is finished processing
26 is finished processing
27 is finished processing
30 is finished processing
32 is finished processing
33 is finished processing
34 is finished processing
38 is finished processing
41 is finished processing
43 is finished processing
44 is finished processing
45 is finished processing
46 is finished processing
47 is finished processing
50 is finished processing
52 is finished processing
53 is finished processing
55 is finished processing
57 is finished processing
59 is finished processing
60 is finished processing
62 is finished processing
63 is finished processing
66 is finished processing
67 is finished processing
68 is finished processing
69 is finished processing
70 is finished processing
71 is finished processing
73 is finished processing
74 is finished processing
75 is finished processing
76 is finished processing
78 is finished processing
79 is finished processing
81 is finished processing
82 is finished processing
84 is finished processing
85 is finished processing
86 is finished processing
88 is finished processing
90 is finished processing
91 is finished processing
92 is finished processing
93 is finished processing
95 is finished processing
96 is finished processing
97 is finished processing
98 is finished processing
99 is finished processing
100 is finished processing
101 is finished processing
102 is finished processing
104 is finished processing
105 is finished processing
106 is finished processing
107 is finished processing
110 is finished processing
112 is finished processing
113 is finished processing
114 is finished processing
115 is finished processing
116 is finished processing
119 is finished processing
120 is finished processing
121 is finished processing
124 is finished processing
125 is finished processing
128 is finished processing
129 is finished processing
130 is finished processing
131 is finished processing
133 is finished processing
134 is finished processing
137 is finished processing
138 is finished processing
139 is finished processing
141 is finished processing
142 is finished processing
143 is finished processing
145 is finished processing
146 is finished processing
148 is finished processing
149 is finished processing
150 is finished processing
151 is finished processing
153 is finished processing
154 is finished processing
155 is finished processing
156 is finished processing
157 is finished processing
158 is finished processing
160 is finished processing
162 is finished processing
163 is finished processing
164 is finished processing
165 is finished processing
167 is finished processing
169 is finished processing
171 is finished processing
173 is finished processing
175 is finished processing
176 is finished processing
178 is finished processing
179 is finished processing
181 is finished processing
183 is finished processing
184 is finished processing
185 is finished processing
186 is finished processing
188 is finished processing
189 is finished processing
190 is finished processing
191 is finished processing
193 is finished processing
194 is finished processing
195 is finished processing
198 is finished processing
200 is finished processing
201 is finished processing
202 is finished processing
203 is finished processing
204 is finished processing
205 is finished processing
206 is finished processing
207 is finished processing
208 is finished processing
209 is finished processing
212 is finished processing
213 is finished processing
214 is finished processing
215 is finished processing
216 is finished processing
217 is finished processing
219 is finished processing
221 is finished processing
222 is finished processing
223 is finished processing
224 is finished processing
227 is finished processing
228 is finished processing
230 is finished processing
231 is finished processing
232 is finished processing
234 is finished processing
235 is finished processing
236 is finished processing
237 is finished processing
238 is finished processing
239 is finished processing
240 is finished processing
241 is finished processing
242 is finished processing
244 is finished processing
245 is finished processing
246 is finished processing
247 is finished processing
248 is finished processing
249 is finished processing
250 is finished processing
251 is finished processing
252 is finished processing
254 is finished processing
255 is finished processing
256 is finished processing
258 is finished processing
260 is finished processing
262 is finished processing
263 is finished processing
264 is finished processing
266 is finished processing
267 is finished processing
268 is finished processing
269 is finished processing
270 is finished processing
271 is finished processing
272 is finished processing
273 is finished processing
274 is finished processing
277 is finished processing
278 is finished processing
280 is finished processing
281 is finished processing
282 is finished processing
283 is finished processing
284 is finished processing
291 is finished processing
292 is finished processing
293 is finished processing
295 is finished processing
296 is finished processing
297 is finished processing
299 is finished processing
300 is finished processing
301 is finished processing
302 is finished processing
303 is finished processing
304 is finished processing
306 is finished processing
307 is finished processing
310 is finished processing
311 is finished processing
312 is finished processing
314 is finished processing
316 is finished processing
317 is finished processing
319 is finished processing
320 is finished processing
321 is finished processing
324 is finished processing
326 is finished processing
327 is finished processing
329 is finished processing
330 is finished processing
332 is finished processing
333 is finished processing
335 is finished processing
336 is finished processing
337 is finished processing
338 is finished processing
339 is finished processing
340 is finished processing
341 is finished processing
342 is finished processing
343 is finished processing
346 is finished processing
347 is finished processing
349 is finished processing
352 is finished processing
353 is finished processing
355 is finished processing
356 is finished processing
358 is finished processing
359 is finished processing
360 is finished processing
361 is finished processing
363 is finished processing
364 is finished processing
365 is finished processing
366 is finished processing
369 is finished processing
375 is finished processing
376 is finished processing
379 is finished processing
380 is finished processing
381 is finished processing
382 is finished processing
383 is finished processing
384 is finished processing
385 is finished processing
386 is finished processing
387 is finished processing
388 is finished processing
389 is finished processing
390 is finished processing
393 is finished processing
394 is finished processing
395 is finished processing
396 is finished processing
399 is finished processing
400 is finished processing
401 is finished processing
402 is finished processing
404 is finished processing
405 is finished processing
406 is finished processing
407 is finished processing
408 is finished processing
409 is finished processing
410 is finished processing
413 is finished processing
414 is finished processing
415 is finished processing
416 is finished processing
417 is finished processing
419 is finished processing
420 is finished processing
423 is finished processing
425 is finished processing
427 is finished processing
428 is finished processing
430 is finished processing
431 is finished processing
432 is finished processing
433 is finished processing
434 is finished processing
435 is finished processing
436 is finished processing
437 is finished processing
438 is finished processing
439 is finished processing
441 is finished processing
442 is finished processing
443 is finished processing
445 is finished processing
446 is finished processing
447 is finished processing
448 is finished processing
449 is finished processing
450 is finished processing
451 is finished processing
452 is finished processing
453 is finished processing
454 is finished processing
455 is finished processing
456 is finished processing
457 is finished processing
458 is finished processing
459 is finished processing
460 is finished processing
461 is finished processing
462 is finished processing
463 is finished processing
464 is finished processing
466 is finished processing
467 is finished processing
468 is finished processing
470 is finished processing
471 is finished processing
473 is finished processing
476 is finished processing
477 is finished processing
481 is finished processing
482 is finished processing
484 is finished processing
487 is finished processing
488 is finished processing
489 is finished processing
493 is finished processing
495 is finished processing
496 is finished processing
497 is finished processing
498 is finished processing
500 is finished processing
503 is finished processing
504 is finished processing
505 is finished processing
508 is finished processing
510 is finished processing
511 is finished processing
513 is finished processing
515 is finished processing
516 is finished processing
520 is finished processing
521 is finished processing
522 is finished processing
524 is finished processing
525 is finished processing
527 is finished processing
528 is finished processing
530 is finished processing
532 is finished processing
533 is finished processing
535 is finished processing
536 is finished processing
537 is finished processing
538 is finished processing
539 is finished processing
540 is finished processing
542 is finished processing
543 is finished processing
545 is finished processing
546 is finished processing
548 is finished processing
549 is finished processing
550 is finished processing
551 is finished processing
552 is finished processing
554 is finished processing
556 is finished processing
559 is finished processing
561 is finished processing
565 is finished processing
568 is finished processing
569 is finished processing
570 is finished processing
571 is finished processing
572 is finished processing
573 is finished processing
574 is finished processing
577 is finished processing
578 is finished processing
580 is finished processing
582 is finished processing
583 is finished processing
584 is finished processing
585 is finished processing
587 is finished processing
588 is finished processing
589 is finished processing
590 is finished processing
592 is finished processing
594 is finished processing
596 is finished processing
597 is finished processing
598 is finished processing
599 is finished processing
602 is finished processing
605 is finished processing
606 is finished processing
607 is finished processing
609 is finished processing
610 is finished processing
611 is finished processing
613 is finished processing
615 is finished processing
616 is finished processing
617 is finished processing
620 is finished processing
621 is finished processing
623 is finished processing
625 is finished processing
626 is finished processing
627 is finished processing
629 is finished processing
630 is finished processing
632 is finished processing
633 is finished processing
634 is finished processing
635 is finished processing
636 is finished processing
637 is finished processing
638 is finished processing
639 is finished processing
641 is finished processing
642 is finished processing
644 is finished processing
645 is finished processing
646 is finished processing
647 is finished processing
650 is finished processing
651 is finished processing
653 is finished processing
654 is finished processing
657 is finished processing
659 is finished processing
660 is finished processing
663 is finished processing
664 is finished processing
665 is finished processing
666 is finished processing
668 is finished processing
669 is finished processing
672 is finished processing
675 is finished processing
676 is finished processing
677 is finished processing
679 is finished processing
680 is finished processing
681 is finished processing
682 is finished processing
683 is finished processing
684 is finished processing
685 is finished processing
686 is finished processing
687 is finished processing
688 is finished processing
689 is finished processing
691 is finished processing
692 is finished processing
693 is finished processing
695 is finished processing
696 is finished processing
697 is finished processing
699 is finished processing
700 is finished processing
701 is finished processing
702 is finished processing
703 is finished processing
705 is finished processing
710 is finished processing
711 is finished processing
712 is finished processing
713 is finished processing
716 is finished processing
718 is finished processing
722 is finished processing
723 is finished processing
724 is finished processing
725 is finished processing
726 is finished processing
727 is finished processing
728 is finished processing
729 is finished processing
730 is finished processing
732 is finished processing
733 is finished processing
736 is finished processing
738 is finished processing
739 is finished processing
740 is finished processing
741 is finished processing
742 is finished processing
743 is finished processing
745 is finished processing
747 is finished processing
750 is finished processing
751 is finished processing
752 is finished processing
753 is finished processing
754 is finished processing
755 is finished processing
756 is finished processing
758 is finished processing
759 is finished processing
760 is finished processing
763 is finished processing
764 is finished processing
765 is finished processing
766 is finished processing
767 is finished processing
769 is finished processing
770 is finished processing
772 is finished processing
773 is finished processing
774 is finished processing
775 is finished processing
776 is finished processing
778 is finished processing
779 is finished processing
780 is finished processing
784 is finished processing
785 is finished processing
787 is finished processing
788 is finished processing
790 is finished processing
791 is finished processing
792 is finished processing
793 is finished processing
794 is finished processing
795 is finished processing
796 is finished processing
797 is finished processing
798 is finished processing
799 is finished processing
800 is finished processing
801 is finished processing
803 is finished processing
805 is finished processing
806 is finished processing
807 is finished processing
810 is finished processing
814 is finished processing
815 is finished processing
816 is finished processing
819 is finished processing
821 is finished processing
823 is finished processing
824 is finished processing
826 is finished processing
829 is finished processing
831 is finished processing
833 is finished processing
834 is finished processing
835 is finished processing
841 is finished processing
842 is finished processing
843 is finished processing
844 is finished processing
845 is finished processing
847 is finished processing
848 is finished processing
850 is finished processing
851 is finished processing
852 is finished processing
853 is finished processing
854 is finished processing
856 is finished processing
858 is finished processing
859 is finished processing
862 is finished processing
863 is finished processing
867 is finished processing
870 is finished processing
874 is finished processing
877 is finished processing
878 is finished processing
879 is finished processing
880 is finished processing
881 is finished processing
883 is finished processing
884 is finished processing
887 is finished processing
888 is finished processing
889 is finished processing
891 is finished processing
892 is finished processing
893 is finished processing
895 is finished processing
897 is finished processing
899 is finished processing
900 is finished processing
902 is finished processing
903 is finished processing
904 is finished processing
905 is finished processing
907 is finished processing
908 is finished processing
909 is finished processing
910 is finished processing
911 is finished processing
913 is finished processing
914 is finished processing
916 is finished processing
917 is finished processing
918 is finished processing
919 is finished processing
920 is finished processing
921 is finished processing
923 is finished processing
925 is finished processing
926 is finished processing
927 is finished processing
928 is finished processing
929 is finished processing
930 is finished processing
931 is finished processing
932 is finished processing
934 is finished processing
935 is finished processing
936 is finished processing
937 is finished processing
939 is finished processing
941 is finished processing
942 is finished processing
943 is finished processing
944 is finished processing
946 is finished processing
947 is finished processing
949 is finished processing
953 is finished processing
954 is finished processing
956 is finished processing
957 is finished processing
958 is finished processing
960 is finished processing
961 is finished processing
962 is finished processing
963 is finished processing
967 is finished processing
968 is finished processing
969 is finished processing
970 is finished processing
971 is finished processing
972 is finished processing
973 is finished processing
974 is finished processing
975 is finished processing
976 is finished processing
977 is finished processing
978 is finished processing
979 is finished processing
980 is finished processing
981 is finished processing
982 is finished processing
983 is finished processing
984 is finished processing
986 is finished processing
987 is finished processing
988 is finished processing
989 is finished processing
992 is finished processing
993 is finished processing
995 is finished processing
996 is finished processing
997 is finished processing
998 is finished processing
999 is finished processing
1000 is finished processing
1001 is finished processing
1002 is finished processing
1004 is finished processing
1005 is finished processing
1008 is finished processing
1009 is finished processing
1011 is finished processing
1012 is finished processing
1013 is finished processing
1014 is finished processing
1016 is finished processing
1017 is finished processing
1018 is finished processing
1019 is finished processing
1021 is finished processing
1023 is finished processing
1025 is finished processing
1026 is finished processing
1027 is finished processing
1029 is finished processing
1030 is finished processing
1031 is finished processing
1033 is finished processing
1036 is finished processing
1037 is finished processing
1039 is finished processing
1041 is finished processing
1042 is finished processing
1043 is finished processing
1044 is finished processing
1045 is finished processing
1046 is finished processing
1047 is finished processing
1048 is finished processing
1049 is finished processing
1052 is finished processing
1053 is finished processing
1054 is finished processing
1055 is finished processing
1056 is finished processing
1057 is finished processing
1058 is finished processing
1059 is finished processing
1060 is finished processing
1061 is finished processing
1062 is finished processing
1063 is finished processing
1064 is finished processing
1065 is finished processing
1066 is finished processing
1067 is finished processing
1068 is finished processing
1069 is finished processing
1070 is finished processing

                       CGM    id  bolus  basal  carbs
date
2018-06-15 19:05:00  396.0     3    NaN    NaN    NaN
2018-06-15 19:10:00  394.0     3    NaN    NaN    NaN
2018-06-15 19:15:00  387.0     3    NaN    NaN    NaN
2018-06-15 19:20:00    NaN     3    NaN    NaN    NaN
2018-06-15 19:25:00  338.0     3    NaN    NaN    NaN
...                    ...   ...    ...    ...    ...
2018-11-28 18:40:00  141.0  1212    NaN    0.0    NaN
2018-11-28 18:45:00  128.0  1212    NaN    0.0    NaN
2018-11-28 18:50:00  125.0  1212    NaN    0.0    NaN
2018-11-28 18:55:00  127.0  1212    NaN    0.0    NaN
2018-11-28 19:00:00  135.0  1212    NaN    0.0    NaN

[95253723 rows x 5 columns]

In [84]:
print(f'New sum after distribution of carbs: {df_final["carbs"].sum():.2f}, should be: {df_carbs["carbs"].sum():.2f}')

New sum after distribution of carbs: 39130874.69, should be: 39130874.69

In [85]:
# Adding exercise label and duration
df_exercise = get_df_from_file(raw_data_file_path, 'LOOPDeviceExercise.txt', parse_datetime=False, sep='|')
df_exercise

/var/folders/q1/5jqy1fgs07j9ptpmdsmmhxnw0000gn/T/ipykernel_93979/2272110270.py:2: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path + file_name, sep=sep)

,PtID,RecID,ParentLOOPDeviceUploadsID,DeviceDtTm,UTCDtTm,ExerciseName,DistanceValue,DistanceUnits,DurationValue,DurationUnits,...,TmZnOffset,OriginName,OriginVers,OriginType,OriginDeviceFirmwrVer,OriginDeviceHardwrVer,OriginDeviceManufact,OriginDeviceModel,OriginOperatingSystVer,OriginProductType
0,1173,1,23177,NaN,2018-09-16 18:34:46,Hiking - 4.37 miles,4.370740,miles,7213.940,seconds,...,NaN,com.apple.HealthKit,5.1.1,service,NaN,"Watch4,2",Apple,Watch,5.1.1,"Watch4,2"
1,1173,2,23177,NaN,2018-09-10 01:31:03,Walking - 0.87 miles,0.866911,miles,639.775,seconds,...,NaN,com.apple.HealthKit,0,service,NaN,NaN,NaN,NaN,5.1.1,"Watch4,2"
2,1173,3,23177,NaN,2018-09-14 18:55:57,Hiking - 4.73 miles,4.728440,miles,8383.710,seconds,...,NaN,com.apple.HealthKit,5.1.1,service,NaN,"Watch4,2",Apple,Watch,5.1.1,"Watch4,2"
3,1173,4,23177,NaN,2018-09-13 22:36:54,Walking - 1.63 miles,1.633190,miles,3206.160,seconds,...,NaN,com.apple.HealthKit,0,service,NaN,NaN,NaN,NaN,5.1.1,"Watch4,2"
4,1173,5,23177,NaN,2018-09-11 18:14:12,Walking - 0.78 miles,0.776254,miles,538.781,seconds,...,NaN,com.apple.HealthKit,0,service,NaN,NaN,NaN,NaN,5.1.1,"Watch4,2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51723,760,55828,1414404,NaN,2019-03-14 21:49:59,Walking - 0.19 miles,0.189719,miles,1806.850,seconds,...,NaN,com.apple.HealthKit,4.3.2,service,NaN,NaN,NaN,NaN,4.3.2,"Watch1,1"
51724,760,55829,1414404,NaN,2019-01-28 17:05:24,Walking - 1.19 miles,1.191470,miles,1856.310,seconds,...,NaN,com.apple.HealthKit,4.3.2,service,NaN,NaN,NaN,NaN,4.3.2,"Watch1,1"
51725,853,55830,1469063,NaN,2019-11-10 18:23:51,Walking - 0.95 miles,0.951186,miles,1291.970,seconds,...,NaN,com.apple.HealthKit,5.3.2,service,NaN,"Watch2,3",Apple Inc.,Watch,5.3.2,"Watch2,3"
51726,853,55831,1469063,NaN,2020-02-15 18:02:45,Walking - 1.43 miles,1.432730,miles,3567.880,seconds,...,NaN,com.apple.HealthKit,6.1.3,service,NaN,"Watch2,3",Apple Inc.,Watch,6.1.3,"Watch2,3"
51727,853,55832,1469063,NaN,2020-02-15 17:36:54,Walking - 0.40 miles,0.395101,miles,776.170,seconds,...,NaN,com.apple.HealthKit,6.1.3,service,NaN,"Watch2,3",Apple Inc.,Watch,6.1.3,"Watch2,3"

In [86]:
print(df_exercise['ExerciseName'].unique())
print(df_exercise['EnergyUnits'].unique())

['Hiking - 4.37 miles' 'Walking - 0.87 miles' 'Hiking - 4.73 miles' ...
 'Dance - 0.41 miles' 'Walking - 13.36 miles' 'Cycling - 2.32 miles']
['kilocalories' nan]

In [87]:
for val in df_exercise['ExerciseName'].unique():
    print(val)

Hiking - 4.37 miles
Walking - 0.87 miles
Hiking - 4.73 miles
Walking - 1.63 miles
Walking - 0.78 miles
Walking - 0.73 miles
Walking - 0.88 miles
Walking - 0.85 miles
Walking - 0.00 miles
Walking - 0.70 miles
Walking - 1.03 miles
Walking - 1.67 miles
Walking - 1.34 miles
Walking - 0.93 miles
Other Activity
Yoga
Walking - 1.62 miles
Walking - 0.74 miles
Running - 4.38 miles
Running - 4.21 miles
Walking - 1.13 miles
Running - 3.24 miles
Walking - 1.52 miles
Running - 4.29 miles
Running - 4.31 miles
High Intensity Interval Training
Running - 0.56 miles
Running - 0.72 miles
Rowing - 0.62 miles
Running - 1.19 miles
Running - 1.18 miles
Running - 3.00 miles
Cycling - 0.00 miles
Running - 2.43 miles
Cycling - 12.00 miles
Swimming - 0.62 miles
Other Activity - 0.00 miles
Running - 3.08 miles
Running - 4.63 miles
Running - 3.95 miles
Running - 5.89 miles
Running - 4.00 miles
Running - 3.61 miles
Running - 4.44 miles
Running - 4.62 miles
Walking - 0.79 miles
Walking - 0.46 miles
Walking - 3.88 miles
Walking - 3.92 miles
Walking - 2.93 miles
Walking - 0.90 miles
Walking - 3.37 miles
Walking - 2.24 miles
Walking - 2.56 miles
Walking - 1.89 miles
Walking - 1.36 miles
Walking - 1.37 miles
Walking - 1.14 miles
Walking - 1.29 miles
Walking - 0.02 miles
Walking - 0.98 miles
Walking - 0.75 miles
Running - 1.80 miles
Running - 2.87 miles
Swimming - 0.84 miles
Walking - 0.63 miles
Running - 1.52 miles
Walking - 0.35 miles
Walking - 0.72 miles
Cycling
Running - 0.03 miles
Walking - 0.59 miles
Walking - 0.24 miles
Walking - 0.84 miles
Running - 1.70 miles
Walking - 0.55 miles
Running - 0.83 miles
Running - 1.84 miles
Walking - 0.83 miles
Walking - 0.92 miles
Walking - 0.47 miles
Walking - 0.05 miles
Walking - 1.32 miles
Walking - 1.47 miles
Walking - 1.54 miles
Walking - 0.48 miles
Walking - 1.79 miles
Walking - 1.46 miles
Walking - 1.44 miles
Functional Strength Training
Walking - 1.39 miles
Walking - 1.56 miles
Walking - 1.41 miles
Walking - 1.68 miles
Hiking - 3.94 miles
Hiking - 3.77 miles
Walking - 1.88 miles
Walking - 1.94 miles
Walking - 4.20 miles
Walking - 1.57 miles
Walking - 1.93 miles
Walking - 4.11 miles
Walking - 4.03 miles
Walking - 1.51 miles
Walking - 2.02 miles
Walking - 1.58 miles
Walking - 1.50 miles
Hiking - 4.95 miles
Walking - 1.23 miles
Walking - 1.48 miles
Walking - 1.30 miles
Walking - 1.31 miles
Hiking - 4.82 miles
Walking - 1.60 miles
Walking - 1.49 miles
Walking - 2.14 miles
Walking - 1.42 miles
Walking - 2.59 miles
Hiking - 4.92 miles
Walking - 1.45 miles
Hiking - 4.89 miles
Hiking - 4.58 miles
Walking - 1.53 miles
Walking - 1.15 miles
Walking - 0.04 miles
Walking - 3.41 miles
Walking - 0.53 miles
Running - 0.90 miles
Running - 1.47 miles
Running - 1.15 miles
Walking - 1.06 miles
Walking - 1.12 miles
Running - 3.10 miles
Rowing
Elliptical
Walking - 0.96 miles
Walking - 3.43 miles
Walking - 2.05 miles
Traditional Strength Training
Snow Sports
Cross Training
Walking - 1.77 miles
Walking - 0.67 miles
Walking - 1.11 miles
Pilates
Walking - 3.94 miles
Walking - 2.43 miles
Running - 1.69 miles
Mixed Metabolic Cardio Training
Running - 4.68 miles
Walking - 0.26 miles
Walking - 0.52 miles
Walking - 1.16 miles
Walking - 0.58 miles
Walking - 1.38 miles
Walking - 0.94 miles
Walking - 0.38 miles
Walking - 0.68 miles
Walking - 0.95 miles
Walking - 1.71 miles
Walking - 1.05 miles
Walking - 0.65 miles
Walking - 0.81 miles
Walking - 0.66 miles
Walking - 0.80 miles
Cycling - 23.39 miles
Cycling - 22.08 miles
Running - 4.32 miles
Running - 1.14 miles
Running - 1.72 miles
Walking - 3.06 miles
Walking - 2.31 miles
Walking - 1.24 miles
Cycling - 14.70 miles
Play
Walking - 1.55 miles
Walking - 0.32 miles
Walking - 1.08 miles
Walking - 1.64 miles
Walking - 0.51 miles
Walking - 0.97 miles
Walking - 1.21 miles
Walking - 1.61 miles
Walking - 1.80 miles
Walking - 1.43 miles
Walking - 1.65 miles
Walking - 1.22 miles
Walking - 1.69 miles
Walking - 1.66 miles
Walking - 0.01 miles
Walking
Walking - 1.83 miles
Walking - 2.20 miles
Walking - 2.12 miles
Walking - 1.82 miles
Walking - 1.81 miles
Walking - 1.90 miles
Walking - 2.19 miles
Walking - 1.96 miles
Walking - 0.16 miles
Walking - 0.03 miles
Walking - 2.04 miles
Walking - 2.62 miles
Walking - 2.25 miles
Walking - 2.41 miles
Walking - 1.59 miles
Walking - 1.10 miles
Walking - 0.71 miles
Running - 3.26 miles
Walking - 1.75 miles
Walking - 2.00 miles
Walking - 1.84 miles
Walking - 0.21 miles
Walking - 2.03 miles
Walking - 0.06 miles
Walking - 0.23 miles
Walking - 2.23 miles
Walking - 1.04 miles
Running - 1.74 miles
Walking - 8.48 miles
Walking - 0.19 miles
Running - 4.37 miles
Walking - 1.07 miles
Walking - 0.61 miles
Walking - 0.37 miles
Running - 3.94 miles
Walking - 0.07 miles
Walking - 0.11 miles
Walking - 2.06 miles
Walking - 0.08 miles
Walking - 2.72 miles
Walking - 0.29 miles
Walking - 1.98 miles
Walking - 1.20 miles
Walking - 1.92 miles
Walking - 1.19 miles
Walking - 1.73 miles
Walking - 1.40 miles
Walking - 1.78 miles
Walking - 2.13 miles
Walking - 2.21 miles
Walking - 0.77 miles
Walking - 0.22 miles
Cycling - 31.18 miles
Cycling - 10.58 miles
Walking - 0.25 miles
Walking - 0.64 miles
Walking - 1.01 miles
Walking - 0.09 miles
Cycling - 12.65 miles
Cycling - 17.33 miles
Walking - 0.17 miles
Walking - 0.45 miles
High Intensity Interval Training - 0.00 miles
Cycling - 13.69 miles
Walking - 0.27 miles
Cycling - 12.92 miles
Walking - 0.60 miles
Cycling - 10.01 miles
Cycling - 56.14 miles
Walking - 0.14 miles
Cycling - 8.85 miles
Cycling - 22.01 miles
Cycling - 14.09 miles
Cycling - 48.70 miles
Cycling - 5.63 miles
Cycling - 20.21 miles
Walking - 0.20 miles
Walking - 0.39 miles
Cycling - 13.71 miles
Walking - 0.62 miles
Cycling - 33.16 miles
Cycling - 13.64 miles
Cycling - 21.22 miles
Walking - 0.82 miles
Cycling - 14.26 miles
Walking - 0.54 miles
Cycling - 11.16 miles
Walking - 0.49 miles
Cycling - 8.61 miles
Cycling - 13.63 miles
Cycling - 30.98 miles
Cycling - 12.94 miles
Walking - 0.56 miles
Cycling - 19.77 miles
Running - 3.15 miles
Swimming - 0.00 miles
Running - 1.46 miles
Running - 3.13 miles
Running - 2.35 miles
Walking - 2.73 miles
Walking - 4.16 miles
Walking - 0.76 miles
Walking - 6.80 miles
Walking - 2.50 miles
Cycling - 3.83 miles
Cycling - 3.81 miles
Walking - 4.39 miles
Walking - 2.66 miles
Walking - 2.85 miles
Walking - 1.28 miles
Walking - 1.70 miles
Cross Training - 13.70 miles
Cross Training - 14.80 miles
Cycling - 10.00 miles
Cycling - 13.60 miles
Cycling - 29.77 miles
Cycling - 21.25 miles
Running - 0.48 miles
Running - 1.06 miles
Running - 3.37 miles
Running - 1.49 miles
Running - 1.23 miles
Running - 3.72 miles
Cycling - 21.69 miles
Functional Strength Training - 0.15 miles
Swimming - 0.99 miles
Walking - 0.91 miles
Walking - 1.35 miles
Downhill Skiing - 12.56 miles
Downhill Skiing - 0.14 miles
Cycling - 11.82 miles
Running - 5.00 miles
Walking - 3.67 miles
Running - 2.17 miles
Running - 2.01 miles
Cycling - 17.64 miles
Running - 1.88 miles
Running - 4.30 miles
Running - 2.07 miles
Swimming - 0.31 miles
Swimming - 0.68 miles
Walking - 0.10 miles
Running - 2.18 miles
Walking - 0.40 miles
Running - 1.83 miles
StairClimbing
Running - 1.37 miles
Running - 2.24 miles
Running - 1.77 miles
Running - 3.65 miles
StairClimbing - 0.00 miles
Traditional Strength Training - 0.00 miles
Elliptical - 3.19 miles
Running - 2.69 miles
Running - 1.30 miles
Walking - 1.02 miles
Running - 1.85 miles
Walking - 2.97 miles
Walking - 4.00 miles
Running - 1.81 miles
Running - 2.20 miles
Running - 1.89 miles
Running - 1.87 miles
Running - 1.43 miles
Hiking - 4.86 miles
Walking - 2.51 miles
Walking - 1.00 miles
Running - 1.17 miles
Traditional Strength Training - 1.14 miles
Walking - 1.33 miles
Walking - 0.89 miles
Cycling - 11.47 miles
Cross Training - 14.40 miles
Running - 0.79 miles
Running - 5.42 miles
Hiking - 4.97 miles
Walking - 0.57 miles
Walking - 1.25 miles
Running - 1.13 miles
Running - 3.09 miles
Walking - 2.49 miles
Walking - 0.42 miles
Walking - 0.43 miles
Walking - 2.27 miles
Running - 3.99 miles
Running - 1.53 miles
Running - 2.09 miles
Running - 1.01 miles
Running - 1.21 miles
Downhill Skiing - 25.24 miles
Swimming - 0.13 miles
Running - 1.65 miles
Running - 0.05 miles
Swimming - 1.24 miles
Running - 1.02 miles
Running - 2.76 miles
Cycling - 0.01 miles
Cycling - 4.23 miles
Cycling - 5.08 miles
Running - 0.60 miles
Cycling - 3.72 miles
Running - 2.16 miles
Running - 2.56 miles
Running
Running - 1.44 miles
Walking - 5.36 miles
Walking - 4.57 miles
Running - 4.90 miles
Cycling - 5.83 miles
Running - 1.75 miles
Running - 0.84 miles
Cycling - 3.46 miles
Mixed Metabolic Cardio Training - 1.02 miles
Walking - 2.17 miles
Running - 3.82 miles
Walking - 2.76 miles
Cycling - 12.29 miles
Running - 0.02 miles
Cross Training - 11.60 miles
Running - 2.14 miles
Walking - 5.88 miles
Cycling - 4.87 miles
Cycling - 11.61 miles
Walking - 0.31 miles
Swimming - 1.14 miles
Walking - 3.13 miles
Cycling - 2.55 miles
Running - 1.41 miles
Running - 2.13 miles
Hiking - 2.06 miles
Hiking - 1.90 miles
Running - 1.63 miles
Hiking - 0.08 miles
Walking - 3.52 miles
Swimming - 0.26 miles
Cycling - 9.98 miles
Running - 0.99 miles
Walking - 1.85 miles
Mixed Metabolic Cardio Training - 1.06 miles
Walking - 0.28 miles
Walking - 1.27 miles
Running - 0.35 miles
Mixed Metabolic Cardio Training - 1.43 miles
Swimming - 1.21 miles
Walking - 2.18 miles
Running - 1.91 miles
Cross Training - 15.80 miles
Cycling - 2.57 miles
Cycling - 2.73 miles
Cycling - 1.35 miles
Cycling - 5.30 miles
Cycling - 16.16 miles
Cycling - 7.24 miles
Cycling - 16.20 miles
Cycling - 19.22 miles
Walking - 3.08 miles
Cycling - 16.13 miles
Cycling - 16.14 miles
Cycling - 16.15 miles
Cycling - 1.68 miles
Cycling - 0.09 miles
Cycling - 1.77 miles
Cycling - 1.78 miles
Cycling - 16.18 miles
Cycling - 16.17 miles
Cycling - 6.34 miles
Cycling - 5.81 miles
Cycling - 19.10 miles
Golf
Walking - 4.37 miles
Cycling - 14.75 miles
Cycling - 21.49 miles
Running - 2.05 miles
Cycling - 0.62 miles
Walking - 2.26 miles
Dance - 1.23 miles
Walking - 1.91 miles
Running - 0.53 miles
Dance - 2.54 miles
Walking - 1.72 miles
Dance - 1.79 miles
Running - 2.22 miles
Running - 0.12 miles
Dance - 2.25 miles
Walking - 0.44 miles
Dance - 2.39 miles
Dance - 1.12 miles
Dance - 1.15 miles
Dance - 2.27 miles
Dance - 1.43 miles
Running - 0.70 miles
Walking - 1.74 miles
Dance - 2.31 miles
Dance - 0.82 miles
Dance - 2.21 miles
Walking - 2.10 miles
Walking - 2.09 miles
Dance - 1.14 miles
Dance - 1.08 miles
Dance - 1.65 miles
Dance - 1.26 miles
Dance - 1.57 miles
Running - 1.42 miles
Running - 2.11 miles
Running - 1.76 miles
Running - 2.49 miles
Dance
Running - 1.33 miles
Running - 1.78 miles
Running - 1.32 miles
Running - 1.36 miles
Running - 1.58 miles
Running - 1.56 miles
Running - 1.08 miles
Running - 1.51 miles
Walking - 0.30 miles
Running - 0.88 miles
Running - 2.34 miles
Running - 3.22 miles
Running - 0.31 miles
Walking - 1.86 miles
Cycling - 13.73 miles
Running - 1.67 miles
Running - 1.27 miles
Running - 1.20 miles
Mixed Metabolic Cardio Training - 1.60 miles
Running - 1.07 miles
Running - 0.41 miles
Running - 2.00 miles
Cycling - 1.12 miles
Swimming - 0.70 miles
Cycling - 0.91 miles
Running - 1.45 miles
Cycling - 1.06 miles
Swimming - 0.75 miles
Cycling - 1.18 miles
Swimming - 0.65 miles
Cycling - 0.92 miles
Cycling - 0.48 miles
Swimming - 0.81 miles
Running - 2.61 miles
Swimming - 0.57 miles
Running - 1.64 miles
Running - 1.61 miles
Dance - 0.29 miles
Dance - 1.09 miles
Running - 0.94 miles
Cycling - 6.72 miles
Walking - 2.34 miles
Walking - 4.60 miles
Swimming - 0.28 miles
Swimming - 0.11 miles
Swimming - 0.23 miles
Swimming - 0.16 miles
Swimming
Downhill Skiing - 4.35 miles
Downhill Skiing - 2.51 miles
Downhill Skiing - 2.46 miles
Downhill Skiing - 1.55 miles
Downhill Skiing - 3.31 miles
Downhill Skiing - 5.61 miles
Downhill Skiing
Swimming - 0.40 miles
Swimming - 0.64 miles
Swimming - 0.72 miles
Swimming - 0.51 miles
Cycling - 16.23 miles
Running - 2.06 miles
Running - 4.92 miles
Downhill Skiing - 9.55 miles
Cycling - 0.79 miles
Walking - 1.87 miles
Running - 2.41 miles
Boxing
Swimming - 1.00 miles
Cycling - 1.72 miles
Walking - 3.04 miles
Cycling - 0.83 miles
Walking - 1.99 miles
Walking - 4.51 miles
Barre
Walking - 2.16 miles
Running - 2.97 miles
Running - 2.10 miles
Running - 1.79 miles
Walking - 0.18 miles
Dance - 1.17 miles
Boxing - 2.61 miles
Cycling - 10.74 miles
Cycling - 2.98 miles
Cycling - 1.88 miles
Cycling - 16.26 miles
Walking - 2.07 miles
Cycling - 1.30 miles
Swimming - 0.82 miles
Cycling - 1.17 miles
Walking - 3.90 miles
Cross Training - 15.00 miles
Running - 2.02 miles
Running - 0.10 miles
Table Tennis - 0.14 miles
Table Tennis - 0.52 miles
Table Tennis
Running - 0.81 miles
Running - 1.22 miles
Running - 2.47 miles
Running - 2.72 miles
Running - 2.29 miles
Mixed Metabolic Cardio Training - 1.58 miles
Walking - 1.18 miles
Walking - 2.86 miles
Running - 2.90 miles
Downhill Skiing - 9.69 miles
Downhill Skiing - 14.40 miles
Running - 2.60 miles
Walking - 2.45 miles
Walking - 5.16 miles
Downhill Skiing - 12.28 miles
Boxing - 2.24 miles
Cycling - 30.34 miles
Cycling - 6.20 miles
Walking - 4.15 miles
Running - 2.46 miles
Mixed Metabolic Cardio Training - 0.20 miles
Walking - 2.57 miles
Walking - 1.97 miles
Walking - 2.52 miles
Walking - 2.15 miles
Cycling - 4.12 miles
Running - 3.23 miles
Running - 3.11 miles
Running - 3.20 miles
Running - 3.32 miles
Cycling - 11.45 miles
Running - 3.31 miles
Cycling - 26.02 miles
Running - 3.41 miles
Running - 3.38 miles
Running - 1.71 miles
Cycling - 10.54 miles
Running - 2.84 miles
Running - 0.87 miles
Cycling - 6.44 miles
Walking - 4.09 miles
Walking - 3.95 miles
Walking - 3.59 miles
Walking - 4.40 miles
Running - 0.27 miles
Running - 1.73 miles
Cycling - 13.39 miles
Swimming - 0.58 miles
Cycling - 0.88 miles
Cycling - 12.96 miles
Running - 4.12 miles
Dance - 1.40 miles
Snowboarding - 14.59 miles
Snowboarding - 6.74 miles
Cross Training - 15.30 miles
Running - 0.46 miles
Walking - 3.78 miles
Running - 3.21 miles
Walking - 4.55 miles
Walking - 4.80 miles
Walking - 3.19 miles
Running - 3.01 miles
Running - 12.05 miles
Running - 2.98 miles
Cycling - 38.45 miles
Cycling - 42.48 miles
Cycling - 21.75 miles
Cycling - 42.65 miles
Cycling - 24.53 miles
Cycling - 36.62 miles
Cycling - 38.13 miles
Cycling - 7.17 miles
Cycling - 64.56 miles
Cycling - 6.23 miles
Cycling - 49.97 miles
Cycling - 2.58 miles
Cycling - 26.16 miles
Cycling - 67.36 miles
Cycling - 28.53 miles
Cycling - 14.05 miles
Cycling - 29.27 miles
Cycling - 37.85 miles
Cycling - 5.95 miles
Cycling - 11.32 miles
Cycling - 7.18 miles
Cycling - 52.38 miles
Cycling - 38.03 miles
Cycling - 55.92 miles
Cycling - 21.36 miles
Cycling - 35.84 miles
Cycling - 76.85 miles
Cycling - 12.76 miles
Cycling - 17.57 miles
Cycling - 3.70 miles
Cycling - 22.04 miles
Cycling - 27.99 miles
Cycling - 72.20 miles
Cycling - 28.98 miles
Cycling - 24.21 miles
Cycling - 79.53 miles
Cycling - 7.63 miles
Cycling - 41.87 miles
Cycling - 58.34 miles
Cycling - 8.89 miles
Cycling - 61.94 miles
Cycling - 35.52 miles
Cycling - 22.95 miles
Cycling - 100.19 miles
Dance - 1.68 miles
Running - 1.29 miles
Cycling - 11.23 miles
Walking - 0.69 miles
Cycling - 7.82 miles
Cycling - 1.25 miles
Walking - 3.80 miles
Walking - 1.09 miles
Running - 0.21 miles
Walking - 0.41 miles
Walking - 2.92 miles
Walking - 0.33 miles
Walking - 2.29 miles
Cycling - 2.27 miles
Cycling - 2.63 miles
Running - 0.67 miles
Running - 0.68 miles
Cycling - 1.24 miles
Cycling - 8.91 miles
Cycling - 2.15 miles
Cycling - 16.64 miles
Cycling - 1.36 miles
Cycling - 27.65 miles
Dance - 1.52 miles
Cycling - 30.67 miles
Cycling - 9.89 miles
Cycling - 69.54 miles
Running - 1.97 miles
Walking - 1.95 miles
Cycling - 7.62 miles
Running - 2.33 miles
Boxing - 2.22 miles
Cycling - 1.50 miles
Cycling - 10.79 miles
Cycling - 16.44 miles
Cycling - 6.30 miles
Cycling - 53.50 miles
Walking - 0.36 miles
Dance - 1.44 miles
Mixed Cardio - 0.01 miles
Cycling - 9.76 miles
Downhill Skiing - 3.14 miles
Walking - 8.17 miles
Walking - 2.22 miles
Walking - 3.16 miles
Walking - 3.15 miles
Walking - 2.64 miles
Running - 0.98 miles
Running - 1.00 miles
Cycling - 3.61 miles
Cycling - 1.23 miles
Cycling - 9.07 miles
Cycling - 8.27 miles
Walking - 1.26 miles
Cycling - 4.58 miles
Running - 2.32 miles
Cycling - 15.63 miles
Running - 1.28 miles
Cycling - 6.99 miles
Preparation And Recovery
Cycling - 15.47 miles
Running - 0.57 miles
Running - 4.10 miles
Running - 2.19 miles
Running - 8.80 miles
Running - 4.39 miles
Running - 3.73 miles
Running - 4.07 miles
Running - 7.90 miles
Running - 3.91 miles
Running - 3.90 miles
Running - 5.33 miles
Running - 5.28 miles
Running - 6.63 miles
Running - 5.38 miles
Running - 5.71 miles
Running - 6.44 miles
Running - 9.03 miles
Running - 5.13 miles
Running - 4.06 miles
Running - 8.30 miles
Running - 0.23 miles
Running - 4.50 miles
Running - 3.30 miles
Running - 3.12 miles
Running - 4.40 miles
Running - 6.79 miles
Running - 6.68 miles
Running - 7.51 miles
Running - 6.60 miles
Running - 8.06 miles
Running - 6.75 miles
Running - 10.81 miles
Running - 5.24 miles
Running - 5.36 miles
Running - 7.10 miles
Running - 13.19 miles
Running - 5.25 miles
Running - 12.09 miles
Running - 6.03 miles
Running - 7.25 miles
Running - 11.24 miles
Running - 5.05 miles
Running - 5.29 miles
Running - 5.11 miles
Running - 3.33 miles
Running - 0.71 miles
Running - 2.12 miles
Running - 3.34 miles
Running - 2.89 miles
Running - 3.02 miles
Running - 1.11 miles
Running - 3.43 miles
Play - 3.93 miles
Hiking - 3.84 miles
Dance - 1.53 miles
Hiking - 4.39 miles
Hiking - 3.82 miles
Dance - 2.46 miles
Hiking - 3.92 miles
Hiking - 3.57 miles
Hiking - 4.15 miles
Hiking - 4.13 miles
Dance - 2.05 miles
Dance - 2.43 miles
Hiking - 2.90 miles
Dance - 1.37 miles
Hiking - 1.01 miles
Hiking - 3.83 miles
Hiking - 4.09 miles
Dance - 2.51 miles
Hiking - 1.71 miles
Hiking - 4.08 miles
Hiking - 5.52 miles
Dance - 3.36 miles
Hiking
Play - 5.52 miles
Dance - 2.84 miles
Hiking - 6.18 miles
Hiking - 5.72 miles
Dance - 1.80 miles
Hiking - 5.81 miles
Hiking - 2.33 miles
Dance - 1.38 miles
Hiking - 5.74 miles
Hiking - 5.54 miles
Hiking - 5.85 miles
Hiking - 4.35 miles
Dance - 1.36 miles
Hiking - 3.99 miles
Hiking - 3.87 miles
Hiking - 3.85 miles
Hiking - 3.86 miles
Dance - 2.88 miles
Hiking - 3.88 miles
Play - 1.37 miles
Hiking - 5.53 miles
Hiking - 3.09 miles
Hiking - 5.02 miles
Hiking - 1.80 miles
Hiking - 4.47 miles
Play - 2.09 miles
Hiking - 5.00 miles
Hiking - 4.12 miles
Hiking - 3.54 miles
Cycling - 14.14 miles
Cycling - 12.90 miles
Running - 0.16 miles
Walking - 2.61 miles
Cycling - 113.36 miles
Cycling - 3.32 miles
Dance - 1.35 miles
Hiking - 3.80 miles
Running - 1.48 miles
Running - 2.95 miles
Running - 0.50 miles
Downhill Skiing - 18.84 miles
Downhill Skiing - 29.03 miles
Walking - 3.30 miles
Boxing - 1.95 miles
Cycling - 21.35 miles
Walking - 4.46 miles
Cycling - 73.63 miles
Hiking - 3.22 miles
Cycling - 4.48 miles
Running - 6.16 miles
Cycling - 11.06 miles
Cycling - 17.37 miles
Cycling - 1.01 miles
Running - 0.62 miles
Walking - 0.15 miles
Cycling - 21.63 miles
Cycling - 20.98 miles
Cross Training - 15.20 miles
Running - 4.18 miles
Cycling - 5.53 miles
Cycling - 6.50 miles
Walking - 2.55 miles
Walking - 2.83 miles
Dance - 1.73 miles
Cycling - 3.05 miles
Cycling - 16.80 miles
Running - 3.77 miles
Running - 5.27 miles
Running - 2.58 miles
Hiking - 1.47 miles
Running - 2.80 miles
Running - 2.40 miles
Cross Training - 1.75 miles
Running - 3.51 miles
Cross Training - 2.23 miles
Cross Training - 0.80 miles
Running - 1.66 miles
Running - 2.39 miles
Running - 2.51 miles
Cycling - 6.71 miles
Cross Training - 1.96 miles
Running - 1.90 miles
Running - 1.62 miles
Running - 2.37 miles
Running - 2.63 miles
Cross Training - 1.19 miles
Cycling - 3.35 miles
Hiking - 4.75 miles
Running - 1.50 miles
Running - 5.02 miles
Running - 4.17 miles
Running - 4.03 miles
Running - 2.79 miles
Running - 3.45 miles
Cycling - 8.49 miles
Cycling - 1.49 miles
Cycling - 1.33 miles
Cycling - 7.10 miles
Walking - 3.07 miles

In [88]:
# Adding exercise label and duration
df_exercise['workout_label'] = df_exercise['ExerciseName'].str.split(' -').str[0]
df_exercise['workout_duration'] = df_exercise['DurationValue'] / 60
df_exercise['calories_burned'] = df_exercise['EnergyValue']
df_exercise = df_exercise.rename(columns={'PtID': 'id'})
df_exercise['UTCDtTm'] = pd.to_datetime(df_exercise['UTCDtTm'])
df_exercise = get_df_with_local_date(df_exercise, 'UTCDtTm', df_time_zone)
df_exercise = df_exercise[['id', 'date', 'workout_label', 'workout_duration', 'calories_burned']]
df_exercise

Subjects: 493
1173 is finished processing
296 is finished processing
1013 is finished processing
829 is finished processing
104 is finished processing
105 is finished processing
467 is finished processing
589 is finished processing
407 is finished processing
605 is finished processing
738 is finished processing
787 is finished processing
511 is finished processing
85 is finished processing
621 is finished processing
462 is finished processing
67 is finished processing
456 is finished processing
970 is finished processing
1081 is finished processing
968 is finished processing
644 is finished processing
859 is finished processing
9 is finished processing
242 is finished processing
388 is finished processing
84 is finished processing
432 is finished processing
508 is finished processing
1093 is finished processing
533 is finished processing
438 is finished processing
998 is finished processing
295 is finished processing
932 is finished processing
1211 is finished processing
1105 is finished processing
55 is finished processing
96 is finished processing
420 is finished processing
743 is finished processing
920 is finished processing
1107 is finished processing
745 is finished processing
867 is finished processing
179 is finished processing
884 is finished processing
570 is finished processing
957 is finished processing
1158 is finished processing
699 is finished processing
1067 is finished processing
741 is finished processing
458 is finished processing
504 is finished processing
833 is finished processing
852 is finished processing
819 is finished processing
470 is finished processing
167 is finished processing
961 is finished processing
353 is finished processing
227 is finished processing
1036 is finished processing
34 is finished processing
457 is finished processing
213 is finished processing
793 is finished processing
949 is finished processing
98 is finished processing
12 is finished processing
759 is finished processing
267 is finished processing
1199 is finished processing
944 is finished processing
495 is finished processing
1152 is finished processing
399 is finished processing
13 is finished processing
1162 is finished processing
120 is finished processing
361 is finished processing
693 is finished processing
992 is finished processing
245 is finished processing
669 is finished processing
680 is finished processing
340 is finished processing
1011 is finished processing
1163 is finished processing
842 is finished processing
302 is finished processing
941 is finished processing
1048 is finished processing
636 is finished processing
116 is finished processing
907 is finished processing
977 is finished processing
1190 is finished processing
202 is finished processing
800 is finished processing
967 is finished processing
637 is finished processing
130 is finished processing
346 is finished processing
405 is finished processing
11 is finished processing
538 is finished processing
60 is finished processing
960 is finished processing
646 is finished processing
626 is finished processing
921 is finished processing
627 is finished processing
92 is finished processing
155 is finished processing
711 is finished processing
312 is finished processing
540 is finished processing
190 is finished processing
284 is finished processing
1009 is finished processing
909 is finished processing
355 is finished processing
145 is finished processing
1125 is finished processing
71 is finished processing
692 is finished processing
191 is finished processing
365 is finished processing
260 is finished processing
415 is finished processing
193 is finished processing
676 is finished processing
705 is finished processing
677 is finished processing
969 is finished processing
503 is finished processing
45 is finished processing
727 is finished processing
271 is finished processing
452 is finished processing
262 is finished processing
660 is finished processing
1116 is finished processing
278 is finished processing
878 is finished processing
27 is finished processing
297 is finished processing
1066 is finished processing
1018 is finished processing
82 is finished processing
664 is finished processing
525 is finished processing
435 is finished processing
657 is finished processing
1086 is finished processing
1122 is finished processing
683 is finished processing
63 is finished processing
449 is finished processing
1153 is finished processing
742 is finished processing
841 is finished processing
805 is finished processing
489 is finished processing
186 is finished processing
1090 is finished processing
446 is finished processing
532 is finished processing
1148 is finished processing
1085 is finished processing
551 is finished processing
464 is finished processing
610 is finished processing
1065 is finished processing
980 is finished processing
364 is finished processing
176 is finished processing
363 is finished processing
796 is finished processing
895 is finished processing
476 is finished processing
1097 is finished processing
310 is finished processing
44 is finished processing
43 is finished processing
106 is finished processing
1112 is finished processing
552 is finished processing
1170 is finished processing
774 is finished processing
1202 is finished processing
688 is finished processing
747 is finished processing
1118 is finished processing
189 is finished processing
498 is finished processing
25 is finished processing
384 is finished processing
684 is finished processing
30 is finished processing
572 is finished processing
751 is finished processing
1043 is finished processing
453 is finished processing
725 is finished processing
936 is finished processing
821 is finished processing
53 is finished processing
38 is finished processing
905 is finished processing
431 is finished processing
666 is finished processing
1120 is finished processing
497 is finished processing
651 is finished processing
668 is finished processing
515 is finished processing
1068 is finished processing
1062 is finished processing
266 is finished processing
1123 is finished processing
235 is finished processing
209 is finished processing
163 is finished processing
319 is finished processing
1055 is finished processing
752 is finished processing
1079 is finished processing
784 is finished processing
41 is finished processing
181 is finished processing
149 is finished processing
874 is finished processing
88 is finished processing
321 is finished processing
1126 is finished processing
925 is finished processing
110 is finished processing
1142 is finished processing
404 is finished processing
1133 is finished processing
463 is finished processing
26 is finished processing
979 is finished processing
477 is finished processing
814 is finished processing
806 is finished processing
578 is finished processing
975 is finished processing
914 is finished processing
238 is finished processing
473 is finished processing
224 is finished processing
893 is finished processing
234 is finished processing
230 is finished processing
972 is finished processing
1167 is finished processing
537 is finished processing
1177 is finished processing
910 is finished processing
879 is finished processing
881 is finished processing
390 is finished processing
394 is finished processing
1071 is finished processing
987 is finished processing
654 is finished processing
791 is finished processing
1042 is finished processing
718 is finished processing
845 is finished processing
767 is finished processing
300 is finished processing
599 is finished processing
772 is finished processing
215 is finished processing
447 is finished processing
151 is finished processing
217 is finished processing
577 is finished processing
471 is finished processing
256 is finished processing
216 is finished processing
851 is finished processing
788 is finished processing
675 is finished processing
554 is finished processing
68 is finished processing
269 is finished processing
982 is finished processing
335 is finished processing
341 is finished processing
1124 is finished processing
205 is finished processing
356 is finished processing
291 is finished processing
1092 is finished processing
753 is finished processing
927 is finished processing
712 is finished processing
277 is finished processing
826 is finished processing
488 is finished processing
1056 is finished processing
1101 is finished processing
785 is finished processing
401 is finished processing
188 is finished processing
131 is finished processing
496 is finished processing
47 is finished processing
121 is finished processing
5 is finished processing
173 is finished processing
146 is finished processing
1187 is finished processing
282 is finished processing
653 is finished processing
1095 is finished processing
1205 is finished processing
1014 is finished processing
142 is finished processing
1019 is finished processing
1181 is finished processing
214 is finished processing
100 is finished processing
877 is finished processing
324 is finished processing
729 is finished processing
1001 is finished processing
79 is finished processing
606 is finished processing
750 is finished processing
580 is finished processing
468 is finished processing
934 is finished processing
307 is finished processing
169 is finished processing
974 is finished processing
1084 is finished processing
268 is finished processing
1154 is finished processing
185 is finished processing
926 is finished processing
115 is finished processing
441 is finished processing
778 is finished processing
434 is finished processing
461 is finished processing
203 is finished processing
556 is finished processing
347 is finished processing
3 is finished processing
402 is finished processing
423 is finished processing
584 is finished processing
956 is finished processing
1057 is finished processing
602 is finished processing
219 is finished processing
592 is finished processing
1176 is finished processing
293 is finished processing
848 is finished processing
1208 is finished processing
16 is finished processing
1191 is finished processing
795 is finished processing
59 is finished processing
50 is finished processing
150 is finished processing
1139 is finished processing
134 is finished processing
983 is finished processing
1064 is finished processing
696 is finished processing
236 is finished processing
484 is finished processing
178 is finished processing
1100 is finished processing
124 is finished processing
755 is finished processing
913 is finished processing
428 is finished processing
639 is finished processing
86 is finished processing
1047 is finished processing
500 is finished processing
301 is finished processing
803 is finished processing
1149 is finished processing
792 is finished processing
481 is finished processing
119 is finished processing
1119 is finished processing
853 is finished processing
1091 is finished processing
831 is finished processing
594 is finished processing
1195 is finished processing
638 is finished processing
588 is finished processing
510 is finished processing
582 is finished processing
524 is finished processing
798 is finished processing
52 is finished processing
917 is finished processing
342 is finished processing
810 is finished processing
493 is finished processing
1045 is finished processing
995 is finished processing
114 is finished processing
754 is finished processing
204 is finished processing
596 is finished processing
550 is finished processing
930 is finished processing
241 is finished processing
973 is finished processing
897 is finished processing
903 is finished processing
343 is finished processing
1070 is finished processing
352 is finished processing
376 is finished processing
760 is finished processing
984 is finished processing
854 is finished processing
716 is finished processing
133 is finished processing
128 is finished processing
1016 is finished processing
380 is finished processing
244 is finished processing
900 is finished processing
1103 is finished processing
280 is finished processing
939 is finished processing
1175 is finished processing
396 is finished processing
251 is finished processing
1169 is finished processing
958 is finished processing
844 is finished processing
107 is finished processing
57 is finished processing
536 is finished processing
623 is finished processing
427 is finished processing
1031 is finished processing
645 is finished processing
97 is finished processing
765 is finished processing
222 is finished processing
249 is finished processing
1178 is finished processing
1104 is finished processing
10 is finished processing
165 is finished processing
607 is finished processing
1074 is finished processing
535 is finished processing
1052 is finished processing
543 is finished processing
617 is finished processing
1210 is finished processing
713 is finished processing
1026 is finished processing
383 is finished processing
1109 is finished processing
539 is finished processing
91 is finished processing
615 is finished processing
414 is finished processing
758 is finished processing
724 is finished processing
1150 is finished processing
337 is finished processing
763 is finished processing
665 is finished processing
569 is finished processing
993 is finished processing
733 is finished processing
1138 is finished processing
254 is finished processing
1137 is finished processing
450 is finished processing
200 is finished processing

,id,date,workout_label,workout_duration,calories_burned
0,1173,2018-09-16 10:34:46,Hiking,120.232333,461.3690
1,1173,2018-09-09 17:31:03,Walking,10.662917,80.9740
2,1173,2018-09-14 10:55:57,Hiking,139.728500,624.4150
3,1173,2018-09-13 14:36:54,Walking,53.436000,166.4610
4,1173,2018-09-11 10:14:12,Walking,8.979683,92.7650
...,...,...,...,...,...
51276,450,2019-09-08 18:58:38,Elliptical,28.102667,155.3220
51277,450,2019-09-05 08:31:08,Walking,37.529500,114.4010
51278,450,2019-08-27 14:07:59,Walking,23.511500,82.3137
51576,200,2019-07-26 14:34:36,Functional Strength Training,38.200000,181.3640
51577,200,2019-07-21 12:25:44,Functional Strength Training,39.783333,186.1360

In [89]:
df_exercise[['workout_duration', 'calories_burned']] = df_exercise[['workout_duration', 'calories_burned']].round()
df_exercise

,id,date,workout_label,workout_duration,calories_burned
0,1173,2018-09-16 10:34:46,Hiking,120.0,461.0
1,1173,2018-09-09 17:31:03,Walking,11.0,81.0
2,1173,2018-09-14 10:55:57,Hiking,140.0,624.0
3,1173,2018-09-13 14:36:54,Walking,53.0,166.0
4,1173,2018-09-11 10:14:12,Walking,9.0,93.0
...,...,...,...,...,...
51276,450,2019-09-08 18:58:38,Elliptical,28.0,155.0
51277,450,2019-09-05 08:31:08,Walking,38.0,114.0
51278,450,2019-08-27 14:07:59,Walking,24.0,82.0
51576,200,2019-07-26 14:34:36,Functional Strength Training,38.0,181.0
51577,200,2019-07-21 12:25:44,Functional Strength Training,40.0,186.0

In [90]:
# Add workout label and duration to the df_final
processed_dfs = []
subject_ids = df_final['id'].unique()
print("Subjects:", len(subject_ids))
for subject_id in subject_ids:
    df_subject = df_final[df_final['id'] == subject_id].copy()
    df_subject.sort_index(inplace=True)

    df_subject_workouts = df_exercise[df_exercise['id'] == subject_id].copy()
    df_subject_workouts.set_index('date', inplace=True)
    df_subject_calburn = df_subject_workouts[['calories_burned']].resample('5min', label='right').sum()
    df_subject_workouts = df_subject_workouts[['workout_label', 'workout_duration']].resample('5min', label='right').last()
    df_subject = pd.merge(df_subject, df_subject_calburn, on="date", how='outer')
    df_subject = pd.merge(df_subject, df_subject_workouts, on="date", how='outer')

    df_subject['id'] = subject_id
    processed_dfs.append(df_subject)
    print(f"{subject_id} is finished processing")

df_final = pd.concat(processed_dfs)
df_final

Subjects: 851
3 is finished processing
4 is finished processing
5 is finished processing
6 is finished processing
7 is finished processing
9 is finished processing
10 is finished processing
11 is finished processing
12 is finished processing
13 is finished processing
15 is finished processing
16 is finished processing
18 is finished processing
19 is finished processing
20 is finished processing
21 is finished processing
24 is finished processing
25 is finished processing
26 is finished processing
27 is finished processing
30 is finished processing
32 is finished processing
33 is finished processing
34 is finished processing
38 is finished processing
41 is finished processing
43 is finished processing
44 is finished processing
45 is finished processing
46 is finished processing
47 is finished processing
50 is finished processing
52 is finished processing
53 is finished processing
55 is finished processing
57 is finished processing
59 is finished processing
60 is finished processing
62 is finished processing
63 is finished processing
66 is finished processing
67 is finished processing
68 is finished processing
69 is finished processing
70 is finished processing
71 is finished processing
73 is finished processing
74 is finished processing
75 is finished processing
76 is finished processing
78 is finished processing
79 is finished processing
81 is finished processing
82 is finished processing
84 is finished processing
85 is finished processing
86 is finished processing
88 is finished processing
90 is finished processing
91 is finished processing
92 is finished processing
93 is finished processing
95 is finished processing
96 is finished processing
97 is finished processing
98 is finished processing
99 is finished processing
100 is finished processing
101 is finished processing
102 is finished processing
104 is finished processing
105 is finished processing
106 is finished processing
107 is finished processing
110 is finished processing
112 is finished processing
113 is finished processing
114 is finished processing
115 is finished processing
116 is finished processing
119 is finished processing
120 is finished processing
121 is finished processing
124 is finished processing
125 is finished processing
128 is finished processing
129 is finished processing
130 is finished processing
131 is finished processing
133 is finished processing
134 is finished processing
137 is finished processing
138 is finished processing
139 is finished processing
141 is finished processing
142 is finished processing
143 is finished processing
145 is finished processing
146 is finished processing
148 is finished processing
149 is finished processing
150 is finished processing
151 is finished processing
153 is finished processing
154 is finished processing
155 is finished processing
156 is finished processing
157 is finished processing
158 is finished processing
160 is finished processing
162 is finished processing
163 is finished processing
164 is finished processing
165 is finished processing
167 is finished processing
169 is finished processing
171 is finished processing
173 is finished processing
175 is finished processing
176 is finished processing
178 is finished processing
179 is finished processing
181 is finished processing
183 is finished processing
184 is finished processing
185 is finished processing
186 is finished processing
188 is finished processing
189 is finished processing
190 is finished processing
191 is finished processing
193 is finished processing
194 is finished processing
195 is finished processing
198 is finished processing
200 is finished processing
201 is finished processing
202 is finished processing
203 is finished processing
204 is finished processing
205 is finished processing
206 is finished processing
207 is finished processing
208 is finished processing
209 is finished processing
212 is finished processing
213 is finished processing
214 is finished processing
215 is finished processing
216 is finished processing
217 is finished processing
219 is finished processing
221 is finished processing
222 is finished processing
223 is finished processing
224 is finished processing
227 is finished processing
228 is finished processing
230 is finished processing
231 is finished processing
232 is finished processing
234 is finished processing
235 is finished processing
236 is finished processing
237 is finished processing
238 is finished processing
239 is finished processing
240 is finished processing
241 is finished processing
242 is finished processing
244 is finished processing
245 is finished processing
246 is finished processing
247 is finished processing
248 is finished processing
249 is finished processing
250 is finished processing
251 is finished processing
252 is finished processing
254 is finished processing
255 is finished processing
256 is finished processing
258 is finished processing
260 is finished processing
262 is finished processing
263 is finished processing
264 is finished processing
266 is finished processing
267 is finished processing
268 is finished processing
269 is finished processing
270 is finished processing
271 is finished processing
272 is finished processing
273 is finished processing
274 is finished processing
277 is finished processing
278 is finished processing
280 is finished processing
281 is finished processing
282 is finished processing
283 is finished processing
284 is finished processing
291 is finished processing
292 is finished processing
293 is finished processing
295 is finished processing
296 is finished processing
297 is finished processing
299 is finished processing
300 is finished processing
301 is finished processing
302 is finished processing
303 is finished processing
304 is finished processing
306 is finished processing
307 is finished processing
310 is finished processing
311 is finished processing
312 is finished processing
314 is finished processing
316 is finished processing
317 is finished processing
319 is finished processing
320 is finished processing
321 is finished processing
324 is finished processing
326 is finished processing
327 is finished processing
329 is finished processing
330 is finished processing
332 is finished processing
333 is finished processing
335 is finished processing
336 is finished processing
337 is finished processing
338 is finished processing
339 is finished processing
340 is finished processing
341 is finished processing
342 is finished processing
343 is finished processing
346 is finished processing
347 is finished processing
349 is finished processing
352 is finished processing
353 is finished processing
355 is finished processing
356 is finished processing
358 is finished processing
359 is finished processing
360 is finished processing
361 is finished processing
363 is finished processing
364 is finished processing
365 is finished processing
366 is finished processing
369 is finished processing
375 is finished processing
376 is finished processing
379 is finished processing
380 is finished processing
381 is finished processing
382 is finished processing
383 is finished processing
384 is finished processing
385 is finished processing
386 is finished processing
387 is finished processing
388 is finished processing
389 is finished processing
390 is finished processing
393 is finished processing
394 is finished processing
395 is finished processing
396 is finished processing
399 is finished processing
400 is finished processing
401 is finished processing
402 is finished processing
404 is finished processing
405 is finished processing
406 is finished processing
407 is finished processing
408 is finished processing
409 is finished processing
410 is finished processing
413 is finished processing
414 is finished processing
415 is finished processing
416 is finished processing
417 is finished processing
419 is finished processing
420 is finished processing
423 is finished processing
425 is finished processing
427 is finished processing
428 is finished processing
430 is finished processing
431 is finished processing
432 is finished processing
433 is finished processing
434 is finished processing
435 is finished processing
436 is finished processing
437 is finished processing
438 is finished processing
439 is finished processing
441 is finished processing
442 is finished processing
443 is finished processing
445 is finished processing
446 is finished processing
447 is finished processing
448 is finished processing
449 is finished processing
450 is finished processing
451 is finished processing
452 is finished processing
453 is finished processing
454 is finished processing
455 is finished processing
456 is finished processing
457 is finished processing
458 is finished processing
459 is finished processing
460 is finished processing
461 is finished processing
462 is finished processing
463 is finished processing
464 is finished processing
466 is finished processing
467 is finished processing
468 is finished processing
470 is finished processing
471 is finished processing
473 is finished processing
476 is finished processing
477 is finished processing
481 is finished processing
482 is finished processing
484 is finished processing
487 is finished processing
488 is finished processing
489 is finished processing
493 is finished processing
495 is finished processing
496 is finished processing
497 is finished processing
498 is finished processing
500 is finished processing
503 is finished processing
504 is finished processing
505 is finished processing
508 is finished processing
510 is finished processing
511 is finished processing
513 is finished processing
515 is finished processing
516 is finished processing
520 is finished processing
521 is finished processing
522 is finished processing
524 is finished processing
525 is finished processing
527 is finished processing
528 is finished processing
530 is finished processing
532 is finished processing
533 is finished processing
535 is finished processing
536 is finished processing
537 is finished processing
538 is finished processing
539 is finished processing
540 is finished processing
542 is finished processing
543 is finished processing
545 is finished processing
546 is finished processing
548 is finished processing
549 is finished processing
550 is finished processing
551 is finished processing
552 is finished processing
554 is finished processing
556 is finished processing
559 is finished processing
561 is finished processing
565 is finished processing
568 is finished processing
569 is finished processing
570 is finished processing
571 is finished processing
572 is finished processing
573 is finished processing
574 is finished processing
577 is finished processing
578 is finished processing
580 is finished processing
582 is finished processing
583 is finished processing
584 is finished processing
585 is finished processing
587 is finished processing
588 is finished processing
589 is finished processing
590 is finished processing
592 is finished processing
594 is finished processing
596 is finished processing
597 is finished processing
598 is finished processing
599 is finished processing
602 is finished processing
605 is finished processing
606 is finished processing
607 is finished processing
609 is finished processing
610 is finished processing
611 is finished processing
613 is finished processing
615 is finished processing
616 is finished processing
617 is finished processing
620 is finished processing
621 is finished processing
623 is finished processing
625 is finished processing
626 is finished processing
627 is finished processing
629 is finished processing
630 is finished processing
632 is finished processing
633 is finished processing
634 is finished processing
635 is finished processing
636 is finished processing
637 is finished processing
638 is finished processing
639 is finished processing
641 is finished processing
642 is finished processing
644 is finished processing
645 is finished processing
646 is finished processing
647 is finished processing
650 is finished processing
651 is finished processing
653 is finished processing
654 is finished processing
657 is finished processing
659 is finished processing
660 is finished processing
663 is finished processing
664 is finished processing
665 is finished processing
666 is finished processing
668 is finished processing
669 is finished processing
672 is finished processing
675 is finished processing
676 is finished processing
677 is finished processing
679 is finished processing
680 is finished processing
681 is finished processing
682 is finished processing
683 is finished processing
684 is finished processing
685 is finished processing
686 is finished processing
687 is finished processing
688 is finished processing
689 is finished processing
691 is finished processing
692 is finished processing
693 is finished processing
695 is finished processing
696 is finished processing
697 is finished processing
699 is finished processing
700 is finished processing
701 is finished processing
702 is finished processing
703 is finished processing
705 is finished processing
710 is finished processing
711 is finished processing
712 is finished processing
713 is finished processing
716 is finished processing
718 is finished processing
722 is finished processing
723 is finished processing
724 is finished processing
725 is finished processing
726 is finished processing
727 is finished processing
728 is finished processing
729 is finished processing
730 is finished processing
732 is finished processing
733 is finished processing
736 is finished processing
738 is finished processing
739 is finished processing
740 is finished processing
741 is finished processing
742 is finished processing
743 is finished processing
745 is finished processing
747 is finished processing
750 is finished processing
751 is finished processing
752 is finished processing
753 is finished processing
754 is finished processing
755 is finished processing
756 is finished processing
758 is finished processing
759 is finished processing
760 is finished processing
763 is finished processing
764 is finished processing
765 is finished processing
766 is finished processing
767 is finished processing
769 is finished processing
770 is finished processing
772 is finished processing
773 is finished processing
774 is finished processing
775 is finished processing
776 is finished processing
778 is finished processing
779 is finished processing
780 is finished processing
784 is finished processing
785 is finished processing
787 is finished processing
788 is finished processing
790 is finished processing
791 is finished processing
792 is finished processing
793 is finished processing
794 is finished processing
795 is finished processing
796 is finished processing
797 is finished processing
798 is finished processing
799 is finished processing
800 is finished processing
801 is finished processing
803 is finished processing
805 is finished processing
806 is finished processing
807 is finished processing
810 is finished processing
814 is finished processing
815 is finished processing
816 is finished processing
819 is finished processing
821 is finished processing
823 is finished processing
824 is finished processing
826 is finished processing
829 is finished processing
831 is finished processing
833 is finished processing
834 is finished processing
835 is finished processing
841 is finished processing
842 is finished processing
843 is finished processing
844 is finished processing
845 is finished processing
847 is finished processing
848 is finished processing
850 is finished processing
851 is finished processing
852 is finished processing
853 is finished processing
854 is finished processing
856 is finished processing
858 is finished processing
859 is finished processing
862 is finished processing
863 is finished processing
867 is finished processing
870 is finished processing
874 is finished processing
877 is finished processing
878 is finished processing
879 is finished processing
880 is finished processing
881 is finished processing
883 is finished processing
884 is finished processing
887 is finished processing
888 is finished processing
889 is finished processing
891 is finished processing
892 is finished processing
893 is finished processing
895 is finished processing
897 is finished processing
899 is finished processing
900 is finished processing
902 is finished processing
903 is finished processing
904 is finished processing
905 is finished processing
907 is finished processing
908 is finished processing
909 is finished processing
910 is finished processing
911 is finished processing
913 is finished processing
914 is finished processing
916 is finished processing
917 is finished processing
918 is finished processing
919 is finished processing
920 is finished processing
921 is finished processing
923 is finished processing
925 is finished processing
926 is finished processing
927 is finished processing
928 is finished processing
929 is finished processing
930 is finished processing
931 is finished processing
932 is finished processing
934 is finished processing
935 is finished processing
936 is finished processing
937 is finished processing
939 is finished processing
941 is finished processing
942 is finished processing
943 is finished processing
944 is finished processing
946 is finished processing
947 is finished processing
949 is finished processing
953 is finished processing
954 is finished processing
956 is finished processing
957 is finished processing
958 is finished processing
960 is finished processing
961 is finished processing
962 is finished processing
963 is finished processing
967 is finished processing
968 is finished processing
969 is finished processing
970 is finished processing
971 is finished processing
972 is finished processing
973 is finished processing
974 is finished processing
975 is finished processing
976 is finished processing
977 is finished processing
978 is finished processing
979 is finished processing
980 is finished processing
981 is finished processing
982 is finished processing
983 is finished processing
984 is finished processing
986 is finished processing
987 is finished processing
988 is finished processing
989 is finished processing
992 is finished processing
993 is finished processing
995 is finished processing
996 is finished processing
997 is finished processing
998 is finished processing
999 is finished processing
1000 is finished processing
1001 is finished processing
1002 is finished processing
1004 is finished processing
1005 is finished processing
1008 is finished processing
1009 is finished processing
1011 is finished processing
1012 is finished processing
1013 is finished processing
1014 is finished processing
1016 is finished processing
1017 is finished processing
1018 is finished processing
1019 is finished processing
1021 is finished processing
1023 is finished processing
1025 is finished processing
1026 is finished processing
1027 is finished processing
1029 is finished processing
1030 is finished processing
1031 is finished processing
1033 is finished processing
1036 is finished processing
1037 is finished processing
1039 is finished processing
1041 is finished processing
1042 is finished processing
1043 is finished processing
1044 is finished processing
1045 is finished processing
1046 is finished processing
1047 is finished processing
1048 is finished processing
1049 is finished processing
1052 is finished processing
1053 is finished processing
1054 is finished processing
1055 is finished processing
1056 is finished processing
1057 is finished processing
1058 is finished processing
1059 is finished processing
1060 is finished processing
1061 is finished processing
1062 is finished processing
1063 is finished processing
1064 is finished processing
1065 is finished processing
1066 is finished processing
1067 is finished processing
1068 is finished processing
1069 is finished processing
1070 is finished processing

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration
date,,,,,,,,
2018-06-15 19:05:00,396.0,3,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-15 19:10:00,394.0,3,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-15 19:15:00,387.0,3,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-15 19:20:00,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-15 19:25:00,338.0,3,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2018-11-28 18:40:00,141.0,1212,NaN,0.0,NaN,NaN,NaN,NaN
2018-11-28 18:45:00,128.0,1212,NaN,0.0,NaN,NaN,NaN,NaN
2018-11-28 18:50:00,125.0,1212,NaN,0.0,NaN,NaN,NaN,NaN
2018-11-28 18:55:00,127.0,1212,NaN,0.0,NaN,NaN,NaN,NaN
2018-11-28 19:00:00,135.0,1212,NaN,0.0,NaN,NaN,NaN,NaN

In [91]:
df_final[df_final['workout_label'].notna()]

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration
date,,,,,,,,
2018-12-02 15:55:00,89.0,3,0.00,0.374,0.0,42.0,Running,25.0
2018-12-15 14:35:00,121.0,3,0.00,0.000,0.0,7.0,Cycling,11.0
2018-12-15 17:20:00,90.0,3,0.00,0.000,0.0,4.0,Cycling,3.0
2018-12-15 17:25:00,96.0,3,0.00,0.000,0.0,1.0,Cycling,7.0
2018-12-15 18:05:00,160.0,3,0.00,0.399,0.0,13.0,Cycling,10.0
...,...,...,...,...,...,...,...,...
2019-12-19 08:20:00,140.0,1211,0.95,1.966,0.0,288.0,Rowing,50.0
2019-12-25 10:00:00,227.0,1211,0.00,0.203,0.0,565.0,Hiking,126.0
2019-12-25 13:35:00,177.0,1211,0.00,1.987,0.0,45.0,Rowing,10.0
2020-01-01 07:10:00,127.0,1211,0.00,0.000,0.0,74.0,Walking,22.0
2020-01-01 08:10:00,111.0,1211,0.00,0.836,0.0,37.0,Walking,12.0

In [92]:
print(f'New sum after distribution of calburn: {df_final["calories_burned"].sum():.2f}, should be: {df_exercise["calories_burned"].sum():.2f}')

New sum after distribution of calburn: 14932794.00, should be: 14932794.00

In [101]:
df_insulin_type = get_df_from_file(raw_data_file_path, 'LOOPDeviceIssueRpt.txt', parse_datetime=False, sep='|', encoding='latin1')
df_insulin_type = df_insulin_type[['PtID', 'InsulinModel']]
df_insulin_type = df_insulin_type.rename(columns={'PtID': 'id', 'InsulinModel': 'insulin_type'})
df_insulin_type

        id                                       insulin_type
0      963  (humalogNovologAdult(ExponentialInsulinModel(a...
1      963  (humalogNovologAdult(ExponentialInsulinModel(a...
2      963  (humalogNovologAdult(ExponentialInsulinModel(a...
3      963  (humalogNovologAdult(ExponentialInsulinModel(a...
4      963       (WalshInsulinModel(actionDuration: 18000.0))
...    ...                                                ...
7131   339  (humalogNovologChild(ExponentialInsulinModel(a...
7132   124  (humalogNovologAdult(ExponentialInsulinModel(a...
7133  1121  (humalogNovologChild(ExponentialInsulinModel(a...
7134   436  (humalogNovologAdult(ExponentialInsulinModel(a...
7135   329  (humalogNovologAdult(ExponentialInsulinModel(a...

[7136 rows x 2 columns]

In [102]:
df_insulin_type['insulin_type'].unique()

array(['(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, initialDelay: 1200.0)',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, initialDelay: 1200.0))',
       '(WalshInsulinModel(actionDuration: 18000.0))',
       '(WalshInsulinModel(actionDuration: 21600.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0, initialDelay: 600.0)',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0, initialDelay: 1200.0)',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0, initialDelay: 1200.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 5100.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0, initialDelay: 600.0))',
       '(WalshInsulinModel(actionDuration: 14400.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 25200.0, peakActivityTime: 3900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4200.0, initialDelay: 1200.0))',
       '(WalshInsulinModel(actionDuration: 19800.0))',
       '(WalshInsulinModel(actionDuration: 22500.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 22500.0, peakActivityTime: 4500.0))',
       '(WalshInsulinModel(actionDuration: 16200.0))',
       '(WalshInsulinModel(actionDuration: 7200.0))',
       '(WalshInsulinModel(actionDuration: 8100.0))',
       '(WalshInsulinModel(actionDuration: 17100.0))',
       '(WalshInsulinModel(actionDuration: 9000.0))',
       '(WalshInsulinModel(actionDuration: 10800.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, initialDelay: 300.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, initialDelay: 900.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, initialDelay: 600.0))',
       '(WalshInsulinModel(actionDuration: 25200.0))',
       '(WalshInsulinModel(actionDuration: 13500.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 5100.0, initialDelay: 1200.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 3900.0))',
       '(WalshInsulinModel(actionDuration: 11700.0))',
       '(WalshInsulinModel(actionDuration: 18900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 10800.0, peakActivityTime: 3600.0))',
       '(WalshInsulinModel(actionDuration: 20700.0))',
       '* insulinModel: nil',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 10800.0, peakActivityTime: 3900.0, initialDelay: 1200.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 3900.0, initialDelay: 1200.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 19800.0, peakActivityTime: 3900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 15600.0, peakActivityTime: 3600.0, initialDelay: 1200.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 3900.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 3300.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 14400.0, peakActivityTime: 4500.0, initialDelay: 1200.0))',
       '(WalshInsulinModel(actionDuration: 12600.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0, initialDelay: 900.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 14400.0, peakActivityTime: 4500.0))',
       '(WalshInsulinModel(actionDuration: 9900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 10800.0, peakActivityTime: 3900.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 15600.0, peakActivityTime: 4200.0, initialDelay: 1200.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4800.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 15600.0, peakActivityTime: 4500.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 19200.0, peakActivityTime: 3000.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 4200.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 16200.0, peakActivityTime: 4500.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21000.0, peakActivityTime: 3900.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 14400.0, peakActivityTime: 3900.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0, delay: 600.0)',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0, delay: 600.0)',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 4500.0, delay: 600.0)',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21000.0, peakActivityTime: 3000.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 20700.0, peakActivityTime: 3900.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 20700.0, peakActivityTime: 3600.0))',
       '(humalogNovologChild(ExponentialInsulinModel(actionDuration: 16200.0, peakActivityTime: 3900.0, delay: 600.0)',
       '(WalshInsulinModel(actionDuration: 18000.0, delay: 600.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21300.0, peakActivityTime: 3300.0, delay: 600.0)',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 16200.0, peakActivityTime: 4500.0, delay: 600.0)',
       '(WalshInsulinModel(actionDuration: 28800.0, delay: 600.0))',
       '(WalshInsulinModel(actionDuration: 14400.0, delay: 600.0))',
       '(WalshInsulinModel(actionDuration: 16200.0, delay: 600.0))',
       '(WalshInsulinModel(actionDuration: 18900.0, delay: 600.0))',
       '(WalshInsulinModel(actionDuration: 19800.0, delay: 600.0))',
       '(humalogNovologAdult(ExponentialInsulinModel(actionDuration: 18000.0, peakActivityTime: 4500.0, delay: 600.0)',
       '(WalshInsulinModel(actionDuration: 21600.0, delay: 600.0))',
       '(fiasp(ExponentialInsulinModel(actionDuration: 21120.0, peakActivityTime: 3120.0, delay: 720.0)'],
      dtype=object)

In [107]:
df_insulin_type['insulin_type'] = df_insulin_type['insulin_type'].str.split('(').str[1]
df_insulin_type = df_insulin_type[df_insulin_type['insulin_type'].notna()]
df_insulin_type

/var/folders/q1/5jqy1fgs07j9ptpmdsmmhxnw0000gn/T/ipykernel_93979/79857320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_insulin_type['insulin_type'] = df_insulin_type['insulin_type'].str.split('(').str[1]

        id         insulin_type insulin_type_formatted
0      963  humalogNovologAdult    humalogNovologAdult
1      963  humalogNovologAdult    humalogNovologAdult
2      963  humalogNovologAdult    humalogNovologAdult
3      963  humalogNovologAdult    humalogNovologAdult
4      963    WalshInsulinModel      WalshInsulinModel
...    ...                  ...                    ...
7131   339  humalogNovologChild    humalogNovologChild
7132   124  humalogNovologAdult    humalogNovologAdult
7133  1121  humalogNovologChild    humalogNovologChild
7134   436  humalogNovologAdult    humalogNovologAdult
7135   329  humalogNovologAdult    humalogNovologAdult

[7132 rows x 3 columns]

In [108]:
def add_single_value_to_subjects(df, df_new_val, col_name):
    # TODO: this function is very inefficient... add value directly to located rows instead
    processed_dfs = []
    subject_ids = df['id'].unique()
    for subject_id in subject_ids:
        df_subject = df[df['id'] == subject_id].copy()
        df_subject.sort_index(inplace=True)
    
        user_data = df_new_val[df_new_val['id'] == subject_id].copy()
        if not user_data.empty:
            df_subject[col_name] = user_data[col_name].iloc[0]
        else:
            df_subject[col_name] = np.nan        
        processed_dfs.append(df_subject)
        
    df = pd.concat(processed_dfs)
    return df

In [109]:
# Add insulin type
df_final = add_single_value_to_subjects(df_final, df_insulin_type, 'insulin_type')
df_final

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration,insulin_type
date,,,,,,,,,
2018-06-15 19:05:00,396.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild
2018-06-15 19:10:00,394.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild
2018-06-15 19:15:00,387.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild
2018-06-15 19:20:00,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild
2018-06-15 19:25:00,338.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild
...,...,...,...,...,...,...,...,...,...
2018-11-28 18:40:00,141.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult
2018-11-28 18:45:00,128.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult
2018-11-28 18:50:00,125.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult
2018-11-28 18:55:00,127.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult
2018-11-28 19:00:00,135.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult

In [111]:
# Add age
df_age = get_df_from_file(raw_data_file_path, 'PtRoster.txt', parse_datetime=False, sep='|')
df_age = df_age[['PtID', 'AgeAtEnrollment']]
df_age = df_age.rename(columns={'PtID': 'id', 'AgeAtEnrollment': 'age'})
df_age

       id  age
0     963   16
1      55   34
2    1082   29
3    1173   23
4     296   47
..    ...  ...
914   913   10
915   459    6
916   409    9
917   854   11
918   329   13

[919 rows x 2 columns]

In [112]:
# Add age
df_final = add_single_value_to_subjects(df_final, df_age, 'age')
df_final.head()

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration,insulin_type,age
date,,,,,,,,,,
2018-06-15 19:05:00,396.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8
2018-06-15 19:10:00,394.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8
2018-06-15 19:15:00,387.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8
2018-06-15 19:20:00,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8
2018-06-15 19:25:00,338.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8

In [123]:
# Add gender
df_user_data = get_df_from_file(raw_data_file_path, 'Surveys.txt', parse_datetime=False, sep='|')
df_user_data = df_user_data[['SubjectID', 'gender', 'weight', 'height_feet', 'height_inches']]
df_user_data = df_user_data.dropna(how='all', subset=['gender', 'weight', 'height_feet', 'height_inches'])
# Weight in kg
df_user_data['weight'] = df_user_data.apply(
    lambda row: row['weight'] * 0.453592,
    axis=1
)
# Height in cm
df_user_data['height'] = df_user_data.apply(
    lambda row: (row['height_feet'] * 30.48) + (row['height_inches'] * 2.54),
    axis=1
)
# Gender from int to string
df_user_data['gender'] = df_user_data['gender'].map({1: 'Male', 2: 'Female', 3: 'Non-binary'})

df_user_data = df_user_data[['SubjectID', 'gender', 'weight', 'height']]
df_user_data[['weight', 'height']] = df_user_data[['weight', 'height']].round(1)
df_user_data = df_user_data.rename(columns={'SubjectID': 'id'})
df_user_data

        id  gender  weight  height
0        4    Male    99.8   198.1
2        5  Female   108.9   167.6
5        6    Male    59.0   175.3
8        7    Male    35.4   144.8
11       9  Female    74.8   157.5
...    ...     ...     ...     ...
2188  1208  Female    44.0   139.7
2191  1209    Male    14.7    91.4
2194  1210  Female    64.9   157.5
2197  1211  Female    70.3   167.6
2200  1212  Female    65.8   152.4

[816 rows x 4 columns]

In [124]:
# Add weight, height, and gender
df_final = add_single_value_to_subjects(df_final, df_user_data, 'weight')
df_final = add_single_value_to_subjects(df_final, df_user_data, 'height')
df_final = add_single_value_to_subjects(df_final, df_user_data, 'gender')
df_final.head()

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration,insulin_type,age,weight,height,gender
date,,,,,,,,,,,,,
2018-06-15 19:05:00,396.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:10:00,394.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:15:00,387.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:20:00,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:25:00,338.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN

### Save Resampled Data

In [125]:
df_final

,CGM,id,bolus,basal,carbs,calories_burned,workout_label,workout_duration,insulin_type,age,weight,height,gender
date,,,,,,,,,,,,,
2018-06-15 19:05:00,396.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:10:00,394.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:15:00,387.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:20:00,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
2018-06-15 19:25:00,338.0,3,NaN,NaN,NaN,NaN,NaN,NaN,humalogNovologChild,8,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-28 18:40:00,141.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult,12,65.8,152.4,Female
2018-11-28 18:45:00,128.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult,12,65.8,152.4,Female
2018-11-28 18:50:00,125.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult,12,65.8,152.4,Female
2018-11-28 18:55:00,127.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult,12,65.8,152.4,Female
2018-11-28 19:00:00,135.0,1212,NaN,0.0,NaN,NaN,NaN,NaN,humalogNovologAdult,12,65.8,152.4,Female

In [126]:
save_file_path = "../../data/resampled/"
os.makedirs(save_file_path, exist_ok=True)
df_final.to_csv(save_file_path + 'Loop.csv')

In [ ]:
# TODO: Split into smaller files???

In [127]:
# Split into smaller partitions, by ids so that a single id is always in a single file
save_file_path = "../../data/resampled/"
os.makedirs(save_file_path, exist_ok=True)
id_column = 'id'
unique_ids = df_final[id_column].unique()
np.random.shuffle(unique_ids) 
split = 8
id_splits = np.array_split(unique_ids, split)  # Split into 8 files

for i, id_subset in enumerate(id_splits, start=1):
    subset_df = df_final[df_final[id_column].isin(id_subset)]
    save_file_name = f"Loop_Part{i}_of_{split}.csv"
    subset_df.to_csv(f"{save_file_path}{save_file_name}", index=False)
    print(f"Saved {save_file_path}{save_file_name} with {len(subset_df)} rows")

Saved ../../data/resampled/Loop_Part1_of_8.csv with 11556695 rows
Saved ../../data/resampled/Loop_Part2_of_8.csv with 11970501 rows
Saved ../../data/resampled/Loop_Part3_of_8.csv with 12311910 rows
Saved ../../data/resampled/Loop_Part4_of_8.csv with 12115837 rows
Saved ../../data/resampled/Loop_Part5_of_8.csv with 12252085 rows
Saved ../../data/resampled/Loop_Part6_of_8.csv with 11948283 rows
Saved ../../data/resampled/Loop_Part7_of_8.csv with 12221154 rows
Saved ../../data/resampled/Loop_Part8_of_8.csv with 11977438 rows

In [128]:
total_rows_before = len(df_final)
total_rows_after = sum(len(df_final[df_final[id_column].isin(subset)]) for subset in id_splits)

print(f"Total rows before split: {total_rows_before}")
print(f"Total rows after split: {total_rows_after}")

Total rows before split: 96353903
Total rows after split: 96353903

In [129]:
print(df_final[id_column].isna().sum())  # Check missing IDs

0

In [6]:
# Paths to files
full_file = "../../data/resampled/Loop.csv"
split_folder = "../../data/resampled/"
split_files = [f for f in os.listdir(split_folder) if f.startswith("Loop_Part") and f.endswith(".csv")]

# Column with unique subject IDs (change if needed)
id_column = "id"

# Read full file
df_full = pd.read_csv(full_file, low_memory=False)
total_rows_full = len(df_full)
unique_ids_full = df_full[id_column].nunique()

# Print comparison
print("📌 **Full File Stats**")
print(f"Total rows: {total_rows_full}")
print(f"Unique subjects: {unique_ids_full}")

# Read split files and merge row counts
total_rows_split = 0
unique_ids_split = set()

for file in split_files:
    df_part = pd.read_csv(os.path.join(split_folder, file), low_memory=False)
    total_rows_split += len(df_part)
    print("total_rows_split ", total_rows_split)
    unique_ids_split.update(df_part[id_column].unique())  # Store unique IDs

unique_ids_split_count = len(unique_ids_split)

print("\n📌 **Split Files Stats**")
print(f"Total rows across all parts: {total_rows_split}")
print(f"Unique subjects across all parts: {unique_ids_split_count}")

# Check if data matches
if total_rows_full == total_rows_split and unique_ids_full == unique_ids_split_count:
    print("\n✅ The split files correctly contain all data!")
else:
    print("\n⚠️ Data Mismatch! Some rows or subjects may be missing.")

📌 **Full File Stats**
Total rows: 96353903
Unique subjects: 851
total_rows_split  12221154
total_rows_split  24169437
total_rows_split  35726132
total_rows_split  47841969
total_rows_split  60094054
total_rows_split  72071492
total_rows_split  84383402
total_rows_split  96353903

📌 **Split Files Stats**
Total rows across all parts: 96353903
Unique subjects across all parts: 851

✅ The split files correctly contain all data!